import React,{FormEvent,useEffect,useMemo,useState}from'react';
import{ArrowLeft,FileText,Plus,Search,Users,X}from'lucide-react';
import'../css/clients-page.css';

type Client={id:number;name:string;document:string;phone:string;postal_code:string;street:string;number:string;district:string;city:string;state:string;complement?:string;whatsapp_url?:string;maps_url?:string};
type Errors=Record<string,string[]>;
type Props={quick?:boolean;onSelected?:(client:Client)=>void;openOrder?:(id:number)=>void;role?:string};
type OrderItem={id?:number;description:string;quantity:number;unit_price_cents:number;subtotal_cents:number};
type ClientOrder={id:number;number:string;status:string;received_at:string;reported_problem:string;result?:string|null;total_cents?:number;items?:OrderItem[];documents?:Array<{revision:number}>};

const ICONS={whatsapp:'/arl-assets/icons/icon-whatsapp.png',maps:'/arl-assets/icons/icon-maps.png',visualizar:'/arl-assets/icons/icon-visualizar.png',editar:'/arl-assets/icons/icon-editar.png',lixeira:'/arl-assets/icons/icon-lixeira.png'} as const;
const emptyClient={name:'',document:'',phone:'',postal_code:'',street:'',number:'',district:'',city:'',state:'',complement:''};
const status:Record<string,string>={analysis:'Em Análise',waiting_part:'Aguardando Peça',in_service:'Em Serviço',completed:'Concluído',interrupted:'Interrompido'};
const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';
const api=async(url:string,options:RequestInit={})=>{const r=await fetch('/api'+url,{credentials:'same-origin',...options,headers:{Accept:'application/json',...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(csrf()?{'X-CSRF-TOKEN':csrf()}:{}),...options.headers}});const json=await r.json().catch(()=>({message:'Resposta inválida do servidor.'}));if(!r.ok)throw Object.assign(new Error(json.message||'Não foi possível concluir.'),{errors:json.errors});return json};
const digits=(value:string)=>value.replace(/\D/g,'');
const masks={document:(v:string)=>{const n=digits(v).slice(0,14);return n.length<=11?n.replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2'):n.replace(/(\d{2})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1/$2').replace(/(\d{4})(\d)/,'$1-$2')},phone:(v:string)=>digits(v).slice(0,11).replace(/^(\d{2})(\d)/,'($1) $2').replace(/(\d{5})(\d)/,'$1-$2'),cep:(v:string)=>digits(v).slice(0,8).replace(/(\d{5})(\d)/,'$1-$2')};
const normalized=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
const money=(cents=0)=>`R$ ${(cents/100).toFixed(2).replace('.',',')}`;

function Field({label,name,value,onChange,error,required=false}:any){return <label className="field"><span>{label}{required&&' *'}</span><input name={name} value={value} onChange={onChange}/>{error&&<small>{error}</small>}</label>}
function ActionIcon({kind}:{kind:keyof typeof ICONS}){return <img className="clients-action-icon" src={ICONS[kind]} alt="" aria-hidden="true"/>}

function ClientModal({client,onSaved,onCancel}:{client?:Client|null;onSaved:(client:Client)=>void;onCancel:()=>void}){
 const[data,setData]=useState<any>(client?{...client}:emptyClient),[errors,setErrors]=useState<Errors>({}),[busy,setBusy]=useState(false),[cepNote,setCepNote]=useState('');
 const change=(e:React.ChangeEvent<HTMLInputElement>)=>{let v=e.target.value;if(e.target.name==='document')v=masks.document(v);if(e.target.name==='phone')v=masks.phone(v);if(e.target.name==='postal_code')v=masks.cep(v);setData((current:any)=>({...current,[e.target.name]:v}))};
 const lookup=async()=>{const cep=digits(data.postal_code);if(cep.length!==8)return;setCepNote('Consultando CEP…');try{const r=await fetch(`https://viacep.com.br/ws/${cep}/json/`);const j=await r.json();if(j.erro)throw Error();setData((current:any)=>({...current,street:j.logradouro||current.street,district:j.bairro||current.district,city:j.localidade||current.city,state:j.uf||current.state}));setCepNote('Endereço preenchido. Você pode corrigir os campos.')}catch{setCepNote('ViaCEP indisponível. Preencha o endereço manualmente.')}};
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setErrors({});try{const saved=await api(client?`/clients/${client.id}`:'/clients',{method:client?'PUT':'POST',body:JSON.stringify({...data,document:digits(data.document),postal_code:digits(data.postal_code)})});onSaved(saved)}catch(x:any){setErrors(x.errors||{form:[x.message]})}finally{setBusy(false)}};
 const title=client?'Editar cliente':'Novo cliente';
 return <div className="clients-modal" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onCancel()}}><section className="clients-modal-card" role="dialog" aria-modal="true" aria-label={title}><button className="clients-modal-close" type="button" aria-label="Fechar" onClick={onCancel}><X/></button><form className="form-card clients-modal-form" onSubmit={submit}><h2><Users/> {title}</h2>{errors.form&&<div className="alert">{errors.form[0]}</div>}<div className="clients-modal-grid"><Field label="Nome / Razão social" name="name" value={data.name} onChange={change} error={errors.name?.[0]} required/><Field label="CPF / CNPJ" name="document" value={data.document} onChange={change} error={errors.document?.[0]} required/><Field label="Telefone" name="phone" value={data.phone} onChange={change} error={errors.phone?.[0]} required/><label className="field"><span>CEP *</span><input name="postal_code" value={data.postal_code} onChange={change} onBlur={lookup}/><small>{errors.postal_code?.[0]||cepNote}</small></label><Field label="Endereço" name="street" value={data.street} onChange={change} error={errors.street?.[0]} required/><Field label="Número" name="number" value={data.number} onChange={change} error={errors.number?.[0]} required/><Field label="Bairro" name="district" value={data.district} onChange={change} error={errors.district?.[0]} required/><Field label="Cidade" name="city" value={data.city} onChange={change} error={errors.city?.[0]} required/><Field label="Estado" name="state" value={data.state} onChange={change} error={errors.state?.[0]} required/><Field label="Complemento" name="complement" value={data.complement||''} onChange={change}/></div><div className="clients-modal-actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar cliente'}</button></div></form></section></div>
}

function ClientHistory({id,onClose,openOrder}:{id:number;onClose:()=>void;openOrder?:(id:number)=>void}){
 const[data,setData]=useState<{client:Client;orders:ClientOrder[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{api('/clients/'+id).then(setData).catch(e=>setError(e.message))},[id]);
 if(error)return <div className="state error">{error}</div>;if(!data)return <div className="state">Carregando histórico…</div>;
 const c=data.client;
 return <section className="clients-react-page clients-history-page" data-arl-clients-react="1"><button className="clients-back" onClick={onClose}><ArrowLeft/>Voltar aos clientes</button><div className="title clients-title"><div><span className="clients-eyebrow">ARL INFORMÁTICA</span><h1>{c.name}</h1><p>Cliente Nº {c.id} · {masks.document(c.document)} · {masks.phone(c.phone)}</p></div></div><section className="panel clients-history-data"><h2>Dados atuais</h2><p>{c.street}, {c.number} — {c.district}, {c.city}/{c.state} · CEP {masks.cep(c.postal_code)}{c.complement?` · ${c.complement}`:''}</p></section><section className="panel client-history"><div className="clients-history-head"><div><h2>Histórico de serviços</h2><p>{data.orders.length} {data.orders.length===1?'ordem registrada':'ordens registradas'}, ordenadas pela data de abertura.</p></div></div>{data.orders.length?data.orders.map(o=>{const final=o.documents?.[0];return <article className="clients-history-order" key={o.id}><div className="clients-history-order-main"><div><b>OS #{o.number}</b><small>{new Date(o.received_at).toLocaleString('pt-BR')} · {status[o.status]||o.status}</small></div><p>{o.reported_problem}</p>{o.items?.length?<ul>{o.items.map((item,i)=><li key={`${o.id}-${item.id||i}`}><span>{item.quantity}× {item.description}</span><strong>{money(item.subtotal_cents??item.quantity*item.unit_price_cents)}</strong></li>)}</ul>:<small>Nenhum serviço/produto registrado nesta OS.</small>}</div><div className="clients-history-order-actions"><strong>{money(o.total_cents||0)}</strong>{openOrder&&<button onClick={()=>openOrder(o.id)}>Ver OS</button>}{final?<a href={`/api/orders/${o.id}/final/${final.revision}/pdf`} target="_blank" rel="noreferrer"><FileText/>2ª via PDF A4</a>:<span className="clients-pdf-pending">PDF disponível após finalização</span>}</div></article>}):<div className="state">Nenhuma OS para este cliente.</div>}</section></section>
}

export default function ClientsPage({quick=false,onSelected,openOrder,role}:Props){
 const[items,setItems]=useState<Client[]>([]),[q,setQ]=useState(''),[sort,setSort]=useState<'name'|'id'>('name'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState<Client|null|true>(quick?true:null),[detail,setDetail]=useState<number>();
 const canManage=!quick&&(role==='Master'||role==='Administrador');
 const load=()=>{setLoading(true);setError('');api('/clients?all=1').then(x=>setItems(x.data||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const needle=normalized(q.trim()),needleDigits=digits(q);const selected=!needle?items:items.filter(c=>normalized(c.name).includes(needle)||normalized(c.phone).includes(needle)||normalized(c.document).includes(needle)||(needleDigits&&[digits(c.phone),digits(c.document)].some(value=>value.includes(needleDigits))));return [...selected].sort((a,b)=>sort==='id'?a.id-b.id:a.name.localeCompare(b.name,'pt-BR',{sensitivity:'base'})||a.id-b.id)},[items,q,sort]);
 const onSaved=(saved:Client)=>{setItems(current=>{const exists=current.some(c=>c.id===saved.id);return exists?current.map(c=>c.id===saved.id?saved:c):[...current,saved]});setModal(null);onSelected?.(saved)};
 const remove=async(c:Client)=>{if(!window.confirm(`Excluir ${c.name} da lista de clientes?\n\nAs OS e documentos históricos serão preservados.`))return;try{await api(`/clients/${c.id}`,{method:'DELETE'});setItems(current=>current.filter(item=>item.id!==c.id))}catch(e:any){window.alert(e.message||'Não foi possível excluir o cliente.')}};
 if(detail)return <ClientHistory id={detail} onClose={()=>setDetail(undefined)} openOrder={openOrder}/>;
 return <section className="clients-react-page" data-arl-clients-react="1"><div className="title clients-title"><div><span className="clients-eyebrow">ARL INFORMÁTICA</span><h1>Gestão de Clientes</h1><p>Gerencie seus clientes com busca instantânea, histórico e cadastro rápido.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus/>Novo cliente</button></div><section className="panel clients-list-panel"><div className="clients-search-head"><div><h2><Search/>Buscar clientes</h2><p>Pesquise por nome, telefone ou CPF/CNPJ</p></div><span>{filtered.length} {filtered.length===1?'cliente encontrado':'clientes encontrados'}</span></div><div className="clients-toolbar"><label className="clients-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, telefone ou CPF/CNPJ…" aria-label="Buscar clientes"/></label><label className="clients-sort">Ordenar<select aria-label="Ordenar clientes" value={sort} onChange={e=>setSort(e.target.value as 'name'|'id')}><option value="name">Alfabética</option><option value="id">Por ID de cadastro</option></select></label></div>{loading?<div className="state">Carregando clientes…</div>:error?<div className="state error">{error}</div>:!filtered.length?<div className="state">Nenhum cliente encontrado.</div>:<div className="client-list">{filtered.map(c=><article className="clients-row" key={c.id}><div className="clients-id"><b>Cliente Nº {c.id}</b></div><div className="clients-main"><b>{c.name}</b><small>{masks.document(c.document)}</small></div><span className="clients-phone">{masks.phone(c.phone)}</span><div className="clients-address"><span>{c.street}, {c.number} · {c.district}</span><small>{c.city} - {c.state}{c.complement?` · ${c.complement}`:''}</small></div><div className="contact-links clients-actions"><a href={c.whatsapp_url} target="_blank" rel="noreferrer" aria-label="WhatsApp" title="Abrir WhatsApp"><ActionIcon kind="whatsapp"/></a><a href={c.maps_url} target="_blank" rel="noreferrer" aria-label="Maps" title="Abrir Google Maps"><ActionIcon kind="maps"/></a>{quick&&onSelected&&<button className="clients-select" onClick={()=>onSelected(c)}>Selecionar</button>}<button aria-label="Visualizar" title="Visualizar cliente" onClick={()=>setDetail(c.id)}><ActionIcon kind="visualizar"/></button>{canManage&&<><button aria-label="Editar" title="Editar cliente" onClick={()=>setModal(c)}><ActionIcon kind="editar"/></button><button aria-label={`Excluir cliente ${c.name}`} title="Excluir cliente" onClick={()=>void remove(c)}><ActionIcon kind="lixeira"/></button></>}</div></article>)}</div>}</section>{modal&&<ClientModal client={modal===true?null:modal} onSaved={onSaved} onCancel={()=>setModal(null)}/>}</section>
}
