import { centsFromMoneyInput, maskMoneyInput, moneyInputFromCents } from './money-input';
import '../css/expense-entry.css';
type Props = { amount: number; mode: string; percent: number; one: string; names: string[]; allowAmounts?: boolean; percentLabel?: string; onChange: (data: { split_mode?: string; percent_one?: number; share_one_value?: string }) => void };
export default function ExpenseSplitFields({ amount, mode, percent, one, names, allowAmounts = true, percentLabel, onChange }: Props) {
  const exact = allowAmounts && mode === 'amount';
  const first = exact ? centsFromMoneyInput(one) : Math.floor((amount * percent + 50) / 100);
  const second = amount - first;
  return <section className="cg-split-fields" aria-label="Divisão de cada parcela"><div className="cg-split-heading"><b>Dividir cada parcela</b>{allowAmounts && <div className="cg-split-modes"><button type="button" aria-pressed={!exact} onClick={() => onChange({ split_mode: 'percent' })}>Por porcentagem</button><button type="button" aria-pressed={exact} onClick={() => onChange({ split_mode: 'amount', share_one_value: moneyInputFromCents(Math.max(0, Math.min(amount, first))) })}>Por valores</button></div>}</div><div className="cg-two-columns">{exact ? <><label>{names[0]} (R$)<input required inputMode="numeric" value={one} onChange={e => onChange({ share_one_value: maskMoneyInput(e.target.value) })} /></label><label>{names[1]} (R$)<input required inputMode="numeric" value={second >= 0 ? moneyInputFromCents(second) : ''} onChange={e => { const value = centsFromMoneyInput(maskMoneyInput(e.target.value)); onChange({ share_one_value: moneyInputFromCents(Math.max(0, amount - value)) }); }} /></label></> : <><label>Parte de {names[0]} (%)<input aria-label={percentLabel} required type="number" min="0" max="100" value={percent} onChange={e => onChange({ percent_one: Number(e.target.value) })} /></label><label>Parte de {names[1]}<output>{100 - percent}% · {moneyInputFromCents(Math.max(0, second))}</output></label></>}</div><small>{second < 0 ? 'A parte informada não pode superar o valor da parcela.' : 'A divisão vale para cada parcela cadastrada. A soma das partes deve corresponder ao valor da parcela.'}{!allowAmounts && ' Em cobranças fixas mensais, a divisão permanece por porcentagem.'}</small></section>;
}
