export {};

type Check = {label:string;note?:string|null};
type Order = {id:number;number:string;status:string;archived?:boolean;attendance_type:'bench'|'external';equipment_type_id:number;reported_problem:string;client:{name:string;phone:string};checklists:Check[]};
type Payment = {transaction_id:number;effective_cents:number};
type Summary = {payments:Payment[];total_cents:number;paid_cents:number;balance_cents:number};
declare global { interface Window { __arlOrderDetailState?: any; __arlOrderDetailRole?: string|null } }
const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';
const api=async(url:string,options:RequestInit={})=>{const r=await fetch('/api'+url,{credentials:'same-origin',...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(csrf()?{'X-CSRF-TOKEN':csrf()}:{}) ,...options.headers}});const b=await r.json().catch(()=>({message:'Resposta inválida.'}));if(!r.ok)throw new Error(b.message||'Não foi possível concluir.');return b};
const reactOrderDetailActive=()=>Boolean(document.querySelector('[data-arl-order-detail-react="1"]'));
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
const money=(c:number)=>`R$ ${(c/100).toFixed(2).replace('.',',')}`;
const icon={edit:'<svg viewBox="0 0 24 24"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg>',pen:'<svg viewBox="0 0 24 24"><path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10Z"/></svg>'};
function styles(){if(document.getElementById('arl-od-actions'))return;const s=document.createElement('style');s.id='arl-od-actions';s.textContent=`.arl-od-tools{margin-left:auto}.arl-od-btn{min-height:34px;border:1px solid #ddd;border-radius:9px;background:#fff;padding:6px 10px;font-size:12px;font-weight:800;display:inline-flex;align-items:center;gap:6px;cursor:pointer}.arl-od-btn svg,.arl-pay-edit svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.arl-od-modal{position:fixed;inset:0;z-index:190;background:#0009;display:grid;place-items:center;padding:14px}.arl-od-card{width:min(620px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:16px;padding:20px;display:grid;gap:12px}.arl-od-card h2{margin:0;font-size:19px}.arl-od-card p{margin:0;color:#737985;font-size:12px}.arl-od-card label{display:grid;gap:5px;font-size:12px;font-weight:800}.arl-od-card select,.arl-od-card textarea,.arl-od-card input{width:100%;border:1px solid #ddd;border-radius:9px;padding:9px;font:inherit}.arl-od-card textarea{min-height:105px}.arl-od-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.arl-od-checks label{display:flex;align-items:center;gap:7px;border:1px solid #eee;border-radius:8px;padding:7px;font-weight:600}.arl-od-checks input{width:auto}.arl-od-actions{display:flex;justify-content:flex-end;gap:7px}.arl-od-actions button,.arl-od-actions a{min-height:36px;border:1px solid #ddd;border-radius:9px;background:#fff;padding:7px 11px;font-weight:800;text-decoration:none;color:inherit;cursor:pointer}.arl-od-actions .primary{background:#c9001c;color:#fff;border-color:#c9001c}.arl-pay-edit{margin-left:7px;width:28px;height:28px}@media(max-width:700px){.arl-od-checks{grid-template-columns:1fr}}`;document.head.append(s)}
function modal(title:string,body:string){document.querySelector('.arl-od-modal')?.remove();const o=document.createElement('div');o.className='arl-od-modal';o.innerHTML=`<section class="arl-od-card"><h2>${esc(title)}</h2>${body}</section>`;document.body.append(o);o.addEventListener('click',e=>{if(e.target===o)o.remove()});return o}
const section=(t:string)=>Array.from(document.querySelectorAll<HTMLElement>('.detail-grid>section')).find(x=>x.querySelector('h2')?.textContent?.trim()===t);
async function edit(order:Order){const templates=await api(`/catalogs/checklist?equipment_type_id=${order.equipment_type_id}`);const selected=new Set(order.checklists.map(x=>x.label));const checks=templates.map((x:any)=>`<label><input type="checkbox" data-id="${x.id}" ${selected.has(x.label)?'checked':''}>${esc(x.label)}</label>`).join('');const o=modal(`Editar OS #${order.number}`,`<p>Corrija o relato e o checklist da OS ativa. Pagamentos são corrigidos separadamente e ficam auditados.</p><label>Atendimento<select data-att><option value="bench">Bancada</option><option value="external">Externo</option></select></label><label>Problema relatado<textarea data-problem spellcheck="true"></textarea></label><label>Checklist selecionado</label><div class="arl-od-checks">${checks||'<span>Nenhuma opção para este equipamento.</span>'}</div><div class="arl-od-actions"><button data-cancel>Cancelar</button><button class="primary" data-save>Salvar alterações</button></div>`);const att=o.querySelector<HTMLSelectElement>('[data-att]')!,problem=o.querySelector<HTMLTextAreaElement>('[data-problem]')!;att.value=order.attendance_type;problem.value=order.reported_problem;o.querySelector('[data-cancel]')?.addEventListener('click',()=>o.remove());o.querySelector<HTMLButtonElement>('[data-save]')?.addEventListener('click',async e=>{const b=e.currentTarget as HTMLButtonElement;b.disabled=true;try{const checklist=Array.from(o.querySelectorAll<HTMLInputElement>('[data-id]:checked')).map(x=>({template_id:Number(x.dataset.id)}));const u=await api(`/orders/${order.id}`,{method:'PATCH',body:JSON.stringify({attendance_type:att.value,reported_problem:problem.value.trim(),checklist})});window.__arlOrderDetailState=u;const p=section('Problema relatado')?.querySelector('p');if(p)p.textContent=u.reported_problem;const c=section('Checklist');if(c){c.querySelectorAll('p').forEach(x=>x.remove());(u.checklists.length?u.checklists:[{label:'Sem avarias marcadas'}]).forEach((x:Check)=>{const q=document.createElement('p');q.textContent=`• ${x.label}`;c.append(q)})}o.remove();sync()}catch(x){b.disabled=false;alert(x instanceof Error?x.message:'Erro ao editar.')}})}
const paymentInFlight=new Set<number>();
async function payment(order:Order){const sec=section('Pagamento');if(!sec)return;const rows=Array.from(sec.querySelectorAll<HTMLElement>('article.transaction'));if(!rows.length)return;if(rows.every(row=>row.querySelector('.arl-pay-edit'))||paymentInFlight.has(order.id))return;paymentInFlight.add(order.id);try{let role=window.__arlOrderDetailRole;if(role==null){role=(await api('/me')).role||'';window.__arlOrderDetailRole=role}if(!['Master','Administrador'].includes(String(role||'')))return;const s=await api(`/orders/${order.id}/payments`) as Summary;const current=section('Pagamento');if(!current)return;const currentRows=Array.from(current.querySelectorAll<HTMLElement>('article.transaction'));s.payments.forEach((p,i)=>{const row=currentRows[i];if(!row||row.querySelector('.arl-pay-edit'))return;const b=document.createElement('button');b.className='arl-pay-edit';b.innerHTML=icon.pen;b.title='Corrigir valor pago';b.addEventListener('click',()=>correct(order,p));row.append(b)})}finally{paymentInFlight.delete(order.id)}}
function correct(order:Order,p:Payment){const o=modal(`Corrigir pagamento da OS #${order.number}`,`<p>A correção mantém o lançamento original e fica auditada.</p><label>Novo valor (R$)<input data-value value="${(p.effective_cents/100).toFixed(2).replace('.',',')}"></label><label>Motivo<textarea data-reason spellcheck="true"></textarea></label><div class="arl-od-actions"><button data-cancel>Cancelar</button><button class="primary" data-save>Salvar correção</button></div>`);o.querySelector('[data-cancel]')?.addEventListener('click',()=>o.remove());o.querySelector('[data-save]')?.addEventListener('click',async()=>{const v=o.querySelector<HTMLInputElement>('[data-value]')!.value,r=o.querySelector<HTMLTextAreaElement>('[data-reason]')!.value.trim(),c=Math.round(Number(v.replace(',','.'))*100);if(!Number.isFinite(c)||c<0||r.length<3){alert('Informe valor e motivo válidos.');return}try{await api(`/finance/transactions/${p.transaction_id}/adjust`,{method:'POST',body:JSON.stringify({new_cents:c,reason:r})});o.remove();const sec=section('Pagamento');if(sec)sec.dataset.payEdit='';sync()}catch(x){alert(x instanceof Error?x.message:'Erro ao corrigir pagamento.')}})}
function tools(order:Order){const h=Array.from(document.querySelectorAll('h1')).find(x=>x.textContent?.trim()===`OS #${order.number}`),title=h?.closest<HTMLElement>('.title');if(!title)return;let wrap=title.querySelector<HTMLElement>('.arl-od-tools');if(order.archived||order.status==='completed'){wrap?.remove();return}if(wrap?.dataset.id===String(order.id))return;wrap?.remove();wrap=document.createElement('div');wrap.className='arl-od-tools';wrap.dataset.id=String(order.id);const b=document.createElement('button');b.className='arl-od-btn';b.innerHTML=`${icon.edit}<span>Editar OS</span>`;b.addEventListener('click',()=>void edit(order));wrap.append(b);title.append(wrap)}
let running=false;function sync(){if(reactOrderDetailActive()||running)return;const order=window.__arlOrderDetailState as Order|undefined;if(!order||!Array.from(document.querySelectorAll('h1')).some(x=>x.textContent?.trim()===`OS #${order.number}`))return;running=true;try{tools(order);void payment(order)}finally{running=false}}
styles();window.addEventListener('arl:order-detail',sync);new MutationObserver(()=>requestAnimationFrame(sync)).observe(document.documentElement,{childList:true,subtree:true});sync();
