export {};

type ClientRow={id:number;name:string;document:string;phone:string};
type OrderRow={id:number;number:string;status:string;archived?:boolean;attendance_type:'bench'|'external';reported_problem:string};
declare global{interface Window{__arlOrderDetailState?:any}}

const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';
const api=async(url:string,options:RequestInit={})=>{const r=await fetch('/api'+url,{credentials:'same-origin',...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(csrf()?{'X-CSRF-TOKEN':csrf()}:{}) ,...options.headers}});const b=await r.json().catch(()=>({message:'Resposta inválida.'}));if(!r.ok)throw new Error(b.message||'Não foi possível concluir.');return b};
const digits=(v:string)=>v.replace(/\D/g,'');
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const trash='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 10v6M14 10v6"/></svg>';
const editIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg>';

let rolePromise:Promise<string>|null=null;
const role=()=>rolePromise??=(api('/me').then(x=>String(x.role||'')).catch(()=>''));
const canManage=async()=>['Master','Administrador'].includes(await role());
const reactClientsActive=()=>Boolean(document.querySelector('[data-arl-clients-react="1"]'));

function installStyles(){if(document.getElementById('arl-record-management-style'))return;const s=document.createElement('style');s.id='arl-record-management-style';s.textContent=`
.clients-workspace:not(.arl-client-editor-open){grid-template-columns:minmax(0,1fr)!important}.clients-workspace:not(.arl-client-editor-open)>.clients-editor{display:none!important}.clients-workspace:not(.arl-client-editor-open)>.clients-list-panel{grid-column:1/-1!important;width:100%!important}.clients-workspace.arl-client-editor-open{align-items:start}.arl-client-delete,.arl-order-delete{width:36px!important;min-width:36px!important;height:36px!important;min-height:36px!important;padding:0!important;border:1px solid #f0bcc5!important;border-radius:10px!important;background:#fff6f8!important;color:#b4001d!important;display:grid!important;place-items:center!important;box-shadow:none!important}.arl-client-delete svg,.arl-order-delete svg,.arl-final-edit svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.contact-links .arl-client-delete{flex:0 0 36px!important}.order-row.arl-has-delete.arl-maintainable>button{margin-right:132px!important}.order-row.arl-has-delete.arl-editable-only>button{margin-right:90px!important}.arl-record-modal{position:fixed;inset:0;z-index:230;background:rgba(10,8,9,.66);display:grid;place-items:center;padding:16px}.arl-record-card{width:min(560px,100%);background:#fff;border-radius:17px;padding:20px;display:grid;gap:12px;box-shadow:0 26px 80px rgba(0,0,0,.3)}.arl-record-card h2{margin:0;font-size:19px}.arl-record-card p{margin:0;color:#717784;font-size:12px;line-height:1.5}.arl-record-card label{display:grid;gap:6px;font-size:12px;font-weight:800}.arl-record-card select,.arl-record-card textarea{width:100%;border:1px solid #ddd;border-radius:9px;padding:9px 10px;font:inherit}.arl-record-card textarea{min-height:120px;resize:vertical}.arl-record-actions{display:flex;justify-content:flex-end;gap:8px}.arl-record-actions button{min-height:36px;border:1px solid #ddd;border-radius:9px;background:#fff;padding:7px 12px;font-weight:800;cursor:pointer}.arl-record-actions .primary{background:#c9001c;color:#fff;border-color:#c9001c}.arl-final-edit{min-height:34px;border:1px solid #ddd;border-radius:9px;background:#fff;padding:6px 10px;font-size:12px;font-weight:800;display:inline-flex;align-items:center;gap:6px;cursor:pointer;margin-left:auto}@media(max-width:900px){.clients-workspace.arl-client-editor-open{grid-template-columns:1fr!important}.order-row.arl-has-delete>button{margin-right:0!important}}
`;document.head.append(s)}

let editorRequested=false,wasClients=false;
function isClientsPage(){return Array.from(document.querySelectorAll('h1')).some(h=>['Gestão de Clientes','Cadastro de Clientes'].includes(h.textContent?.trim()||''))}
function syncClientWorkspace(){if(reactClientsActive()){editorRequested=false;wasClients=false;return}const active=isClientsPage(),workspace=document.querySelector<HTMLElement>('.clients-workspace');if(!active||!workspace){if(wasClients){editorRequested=false;wasClients=false}return}if(!wasClients){editorRequested=false;wasClients=true}workspace.classList.toggle('arl-client-editor-open',editorRequested)}

document.addEventListener('click',event=>{if(reactClientsActive())return;const button=(event.target as Element|null)?.closest<HTMLButtonElement>('button');if(!button)return;const label=button.textContent?.trim()||'';if(isClientsPage()&&(label==='Novo cliente'||label==='Abrir cadastro'||(label==='Editar'&&!!button.closest('.client-list')))){editorRequested=true;requestAnimationFrame(syncClientWorkspace)}if(isClientsPage()&&label==='Cancelar'&&!!button.closest('.clients-editor')){editorRequested=false;requestAnimationFrame(syncClientWorkspace)}},true);

let clientInstallRunning=false;
async function installClientDeletes(){if(reactClientsActive()||clientInstallRunning||!isClientsPage()||!await canManage())return;const cards=Array.from(document.querySelectorAll<HTMLElement>('.client-list article'));if(!cards.length)return;clientInstallRunning=true;try{const search=document.querySelector<HTMLInputElement>('.clients-list-panel .filters input')?.value||'';const page=await api(`/clients?per_page=100&q=${encodeURIComponent(search)}`);const clients=(page.data||[]) as ClientRow[];for(const card of cards){if(card.querySelector('.arl-client-delete'))continue;const name=card.querySelector('b')?.textContent?.trim()||'';const doc=digits(card.querySelector('small')?.textContent||'');const client=clients.find(c=>c.name===name&&digits(c.document)===doc)||clients.find(c=>c.name===name);if(!client)continue;const actions=card.querySelector<HTMLElement>('.contact-links');if(!actions)continue;const b=document.createElement('button');b.type='button';b.className='arl-client-delete';b.title='Excluir cliente';b.setAttribute('aria-label',`Excluir cliente ${client.name}`);b.innerHTML=trash;b.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();if(!confirm(`Excluir ${client.name} da lista de clientes?\n\nAs OS e documentos históricos serão preservados.`))return;b.disabled=true;try{await api(`/clients/${client.id}`,{method:'DELETE'});card.remove();const count=cards.filter(x=>x.isConnected).length;const counter=Array.from(document.querySelectorAll<HTMLElement>('.clients-list-panel *')).find(x=>/clientes? encontrados?/.test((x.textContent||'').toLowerCase())&&x.children.length===0);if(counter)counter.textContent=`${count} ${count===1?'cliente encontrado':'clientes encontrados'}`}catch(x){b.disabled=false;alert(x instanceof Error?x.message:'Não foi possível excluir o cliente.')}});actions.append(b)}}finally{clientInstallRunning=false}}

async function resolveOrder(number:string,finalized:boolean):Promise<OrderRow|null>{const page=await api(`/orders?q=${encodeURIComponent(number)}&finalized=${finalized?'1':'0'}`);return ((page.data||[]) as OrderRow[]).find(o=>String(o.number).replace(/\D/g,'')===number.replace(/\D/g,''))||null}
async function installOrderDeletes(){if(!await canManage())return;const heading=Array.from(document.querySelectorAll('h1')).find(h=>h.textContent?.trim()==='Ordens de Serviço');if(!heading)return;for(const row of Array.from(document.querySelectorAll<HTMLElement>('.order-list .order-row:not(.head)'))){if(row.querySelector('.arl-order-delete'))continue;const number=digits(row.querySelector('b')?.textContent||'');if(!number)continue;let actions=row.querySelector<HTMLElement>('.arl-order-maintenance-actions');if(!actions){actions=document.createElement('div');actions.className='arl-order-maintenance-actions';row.append(actions)}const b=document.createElement('button');b.type='button';b.className='arl-order-mini-action arl-order-delete';b.title='Excluir OS';b.setAttribute('aria-label',`Excluir OS ${number}`);b.innerHTML=trash;b.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();const finalized=!!document.querySelector('.arl-finalized-toggle.active');const order=await resolveOrder(number,finalized);if(!order){alert('Não foi possível localizar esta OS.');return}if(!confirm(`Excluir a OS #${order.number} das listagens?\n\nO financeiro, a auditoria e documentos emitidos serão preservados.`))return;b.disabled=true;try{await api(`/orders/${order.id}`,{method:'DELETE'});row.remove()}catch(x){b.disabled=false;alert(x instanceof Error?x.message:'Não foi possível excluir a OS.')}});actions.append(b);row.classList.add('arl-has-delete')}}

function recordModal(title:string,body:string){document.querySelector('.arl-record-modal')?.remove();const o=document.createElement('div');o.className='arl-record-modal';o.innerHTML=`<section class="arl-record-card" role="dialog" aria-modal="true" aria-label="${esc(title)}"><h2>${esc(title)}</h2>${body}</section>`;document.body.append(o);o.addEventListener('click',e=>{if(e.target===o)o.remove()});return o}
async function installFinalizedEdit(){const order=window.__arlOrderDetailState as OrderRow|undefined;if(!order||(order.status!=='completed'&&!order.archived)||!await canManage())return;const h=Array.from(document.querySelectorAll('h1')).find(x=>x.textContent?.trim()===`OS #${order.number}`),title=h?.closest<HTMLElement>('.title');if(!title||title.querySelector('.arl-final-edit'))return;const b=document.createElement('button');b.type='button';b.className='arl-final-edit';b.innerHTML=`${editIcon}<span>Editar OS</span>`;b.addEventListener('click',()=>{const modal=recordModal(`Editar OS #${order.number}`,`<p>Você pode corrigir o tipo de atendimento e o problema relatado. PDFs já emitidos, pagamentos, serviços finalizados e histórico permanecem preservados.</p><label>Atendimento<select data-att><option value="bench">Bancada</option><option value="external">Externo</option></select></label><label>Problema relatado<textarea data-problem></textarea></label><div class="arl-record-actions"><button data-cancel>Cancelar</button><button class="primary" data-save>Salvar alterações</button></div>`);const att=modal.querySelector<HTMLSelectElement>('[data-att]')!,problem=modal.querySelector<HTMLTextAreaElement>('[data-problem]')!;att.value=order.attendance_type;problem.value=order.reported_problem;modal.querySelector('[data-cancel]')?.addEventListener('click',()=>modal.remove());modal.querySelector<HTMLButtonElement>('[data-save]')?.addEventListener('click',async e=>{const save=e.currentTarget as HTMLButtonElement;save.disabled=true;try{const updated=await api(`/orders/${order.id}`,{method:'PATCH',body:JSON.stringify({attendance_type:att.value,reported_problem:problem.value.trim()})});window.__arlOrderDetailState={...order,...updated};const titleText=title.querySelector('p');if(titleText)titleText.textContent=updated.attendance_type==='bench'?'Análise na Bancada':'Atendimento Externo';const problemText=Array.from(document.querySelectorAll<HTMLElement>('.detail-grid>section')).find(s=>s.querySelector('h2')?.textContent?.trim()==='Problema relatado')?.querySelector('p');if(problemText)problemText.textContent=updated.reported_problem;modal.remove()}catch(x){save.disabled=false;alert(x instanceof Error?x.message:'Não foi possível editar a OS.')}})});title.append(b)}

let syncQueued=false;function sync(){syncQueued=false;syncClientWorkspace();void installClientDeletes();void installOrderDeletes();void installFinalizedEdit()}
function queue(){if(syncQueued)return;syncQueued=true;requestAnimationFrame(sync)}
installStyles();new MutationObserver(queue).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('arl:order-detail',queue);document.addEventListener('DOMContentLoaded',queue);queue();
