import { useEffect, useState, type FormEvent } from 'react';
import { Building2, CalendarDays, ClipboardList, FileText, Package, Plus, Star, TrendingUp } from 'lucide-react';
import OrderPopup from './order-popup';
import { centsFromMoneyInput, maskMoneyInput, moneyInputFromCents } from './money-input';

const money = (v = 0) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(v) / 100);
const date = (v?: string) => v ? v.slice(0, 10).split('-').reverse().join('/') : '—';
const today = () => new Date().toLocaleDateString('sv-SE');
const methods = { pix: 'Pix', cash: 'Dinheiro', bank_transfer: 'Transferência', boleto: 'Boleto', debit_card: 'Débito', credit_card: 'Crédito', cheque: 'Cheque', other: 'Outro' };
const categories: Record<string, string> = { invoice: 'Nota fiscal / XML', boleto: 'Boleto', receipt: 'Comprovante', contract: 'Contrato', prices: 'Tabela de preços', other: 'Outro', delivery: 'Entrega', quality: 'Qualidade', price: 'Preço', service: 'Atendimento' };
const resolutions = { credit: 'Crédito acordado', refund: 'Dinheiro devolvido', exchange: 'Troca combinada', pending: 'Aguardando negociação' };
export async function supplierApi(path: string, options: RequestInit = {}) {
  const response = await fetch('/api' + path, { credentials: 'same-origin', ...options, headers: { Accept: 'application/json', ...(options.body && !(options.body instanceof FormData) ? { 'Content-Type': 'application/json' } : {}), 'X-CSRF-TOKEN': document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content || '', ...options.headers } });
  const body = await response.json();
  if (!response.ok) throw new Error(String(body.errors ? Object.values(body.errors).flat()[0] : body.message || 'Não foi possível concluir.'));
  return body;
}
type Field = { key: string; label: string; type?: string; options?: Record<string, string>; max?: number };
const profileSections: { title: string; fields: Field[] }[] = [
  { title: 'Identificação complementar', fields: [{ key: 'person_type', label: 'Tipo de pessoa', options: { physical: 'Pessoa física', legal: 'Pessoa jurídica' } }, { key: 'state_registration', label: 'Inscrição estadual' }, { key: 'municipal_registration', label: 'Inscrição municipal' }, { key: 'site', label: 'Site', type: 'url' }] },
  { title: 'Representante comercial', fields: [{ key: 'representative', label: 'Nome do representante' }, { key: 'representative_contact', label: 'Contato do representante' }] },
  { title: 'Condições comerciais', fields: [{ key: 'payment_days', label: 'Prazo de pagamento (dias)', type: 'number', max: 365 }, { key: 'payment_method', label: 'Pagamento preferido', options: methods }, { key: 'discount_percent', label: 'Desconto padrão (%)', type: 'number', max: 100 }, { key: 'minimum_order_cents', label: 'Pedido mínimo (R$)', type: 'money' }, { key: 'delivery_days', label: 'Prazo médio de entrega (dias)', type: 'number', max: 365 }, { key: 'freight', label: 'Frete por conta de', options: { supplier: 'Fornecedor', buyer: 'Comprador', negotiated: 'Negociado a cada compra' } }, { key: 'commercial_notes', label: 'Observações comerciais', type: 'textarea' }] },
  { title: 'Banco e Pix', fields: [{ key: 'bank', label: 'Banco' }, { key: 'agency', label: 'Agência' }, { key: 'account', label: 'Conta' }, { key: 'account_type', label: 'Tipo de conta', options: { checking: 'Corrente', savings: 'Poupança', payment: 'Pagamento' } }, { key: 'pix_type', label: 'Tipo da chave Pix', options: { cpf: 'CPF', cnpj: 'CNPJ', email: 'E-mail', phone: 'Telefone', random: 'Aleatória' } }, { key: 'pix_key', label: 'Chave Pix' }] },
];
type Pager = { data: any[]; current_page: number; last_page: number };
type Workspace = { profile: Record<string, any>; summary: Record<string, number>; offerings: any[]; payables: Pager; prices: Pager; occurrences: Pager; returns: Pager; return_items: any[]; documents: any[]; late_purchases: any[]; most_purchased: any[]; ratings: Record<string, number | null>; credit_cents: number; refund_cents: number };

export default function SupplierWorkspace({ id, tab, onPurchase, onChange }: { id: number; tab: string; onPurchase: (id: number) => void; onChange: () => void }) {
  const [data, setData] = useState<Workspace>();
  const [revision, setRevision] = useState(0), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [dialog, setDialog] = useState<string>();
  const [from, setFrom] = useState(''), [to, setTo] = useState('');
  const [pages, setPages] = useState<Record<string, number>>({});
  useEffect(() => {
    const controller = new AbortController(); setError('');
    const params = new URLSearchParams({ ...Object.fromEntries(Object.entries(pages).map(([k, v]) => [k, String(v)])), ...(from ? { from } : {}), ...(to ? { to } : {}) });
    void supplierApi('/suppliers/' + id + '/workspace?' + params, { signal: controller.signal }).then(setData).catch(e => { if (!controller.signal.aborted) setError(e.message); });
    return () => controller.abort();
  }, [id, revision, pages, from, to]);
  const pagination = (key: string, pager: Pager) => pager.last_page > 1 && <div className="supplier-pager"><button disabled={pager.current_page <= 1} onClick={() => setPages(p => ({ ...p, [key]: pager.current_page - 1 }))}>Anterior</button>{pager.current_page}/{pager.last_page}<button disabled={pager.current_page >= pager.last_page} onClick={() => setPages(p => ({ ...p, [key]: pager.current_page + 1 }))}>Próxima</button></div>;
  const metric = (label: string, value: number, amount = true) => <article><small>{label}</small><strong>{amount ? money(value) : value}</strong></article>;
  if (!data) return <section className="supplier-panel">{error ? <p role="alert">{error}</p> : <p role="status">Carregando informações…</p>}</section>;
  return <section className="supplier-workspace">
    {error && <p className="supplier-error" role="alert">{error}</p>}{notice && <p className="supplier-success" role="status">{notice}</p>}
    {tab === 'overview' && <><div className="supplier-workspace-metrics">{metric('Compras registradas', data.summary.purchases, false)}{metric('Total comprado', data.summary.purchased_cents)}{metric('A pagar', data.summary.open_cents)}{metric('Vencido', data.summary.overdue_cents)}</div><div className="supplier-overview-grid"><section className="supplier-panel"><div className="supplier-section-top"><h2><CalendarDays /> O que merece atenção</h2></div>{data.late_purchases.map(p => <button className="supplier-compact-row" key={p.id} onClick={() => onPurchase(p.id)}><span>Compra #{p.id}<small>Entrega prevista: {date(p.expected_on)}</small></span><b>Entrega atrasada</b></button>)}{data.payables.data.filter(p => !p.paid_on && !p.voided_at && p.due_on <= today()).map(p => <button className="supplier-compact-row" key={p.id} onClick={() => onPurchase(p.purchase_id)}><span>Compra #{p.purchase_id} · parcela {p.installment}<small>Vence {date(p.due_on)}</small></span><b>{money(p.amount_cents)}</b></button>)}{!data.late_purchases.length && !data.summary.overdue_cents && <p className="supplier-empty-small">Sem entregas atrasadas ou pagamentos vencidos.</p>}<small>Consulte Financeiro para todas as parcelas.</small></section><section className="supplier-panel"><h2><Star /> Avaliação interna</h2><div className="supplier-rating-summary">{Object.entries({ delivery: 'Entrega', quality: 'Qualidade', price: 'Preço', service: 'Atendimento' }).map(([k, v]) => <div key={k}><span>{v}</span><b>{data.ratings[k] ? Number(data.ratings[k]).toFixed(1) + ' / 5' : 'Sem avaliação'}</b></div>)}</div><button onClick={() => setDialog('occurrence')}><Plus /> Registrar avaliação / ocorrência</button><p className="supplier-muted">Avaliações internas, sem publicação externa.</p></section></div></>}
    {tab === 'commercial' && <><div className="supplier-section-top"><div><h2>Cadastro comercial e bancário</h2><p>Informações opcionais, sem alterar compras antigas.</p></div><button onClick={() => setDialog('profile')}><Building2 /> Editar dados comerciais</button></div><div className="supplier-overview-grid">{profileSections.map(s => <section className="supplier-panel" key={s.title}><h2>{s.title}</h2><dl className="supplier-data-grid">{s.fields.map(f => <div key={f.key}><dt>{f.label}</dt><dd>{data.profile[f.key] == null || data.profile[f.key] === '' ? 'Não informado' : f.type === 'money' ? money(data.profile[f.key]) : f.options?.[data.profile[f.key]] || String(data.profile[f.key])}</dd></div>)}</dl></section>)}</div></>}
    {tab === 'offerings' && <section className="supplier-panel"><div className="supplier-section-top"><div><h2>Produtos fornecidos</h2><p>Vínculos comerciais sem exigir fornecedor no cadastro de produtos.</p></div><button onClick={() => setDialog('offering')}><Plus /> Vincular produto</button></div>{data.offerings.map(o => <article className="supplier-offering" key={o.id}><div><b>{o.name}</b><small>{o.brand || 'Marca não informada'} · código {o.supplier_code || '—'} · {o.active ? 'Ativo' : 'Inativo'}</small></div><span>Último custo recebido<b>{o.last_cost_cents == null ? 'Sem compra' : money(o.last_cost_cents)}</b></span><span>Custo informado<b>{o.cost_cents == null ? 'Não informado' : money(o.cost_cents)}</b></span><span>Mínimo {o.minimum_quantity}<small>Entrega: {o.delivery_days ?? '—'} dias</small></span><button onClick={() => setDialog('offering:' + o.id)}>Editar</button></article>)}{!data.offerings.length && <p className="supplier-empty-small">Vincule os produtos e marcas que este fornecedor oferece.</p>}{data.offerings.some(o => o.cost_cents != null && o.last_cost_cents > 0 && o.cost_cents > Number(o.last_cost_cents) * 1.2) && <p className="supplier-error">Há custos informados mais de 20% acima do último custo recebido. Confira antes de comprar.</p>}</section>}
    {tab === 'finance' && <section className="supplier-panel"><div className="supplier-section-top"><div><h2>Contas a pagar</h2><p>Abra a compra para pagar ou consultar o histórico.</p></div></div><div className="supplier-workspace-metrics">{metric('Pago', data.summary.paid_cents)}{metric('Em aberto', data.summary.open_cents)}{metric('Vencido', data.summary.overdue_cents)}{metric('Créditos acordados em devoluções', data.credit_cents)}</div>{data.payables.data.map(p => <button className="supplier-compact-row" key={p.id} onClick={() => onPurchase(p.purchase_id)}><span>Compra #{p.purchase_id} · parcela {p.installment}<small>Vencimento {date(p.due_on)}</small></span><span className={'supplier-badge ' + (p.paid_on ? 'received' : p.voided_at ? 'cancelled' : 'pending')}>{p.paid_on ? 'Pago em ' + date(p.paid_on) : p.voided_at ? 'Cancelada' : 'Em aberto'}</span><strong>{money(Number(p.amount_cents) + (p.paid_on ? Number(p.interest_cents || 0) - Number(p.discount_cents || 0) : 0))}</strong></button>)}{!data.payables.data.length && <p className="supplier-empty-small">Nenhum título registrado.</p>}{pagination('payments_page', data.payables)}<p className="supplier-muted">Créditos de devolução são acordos registrados; não abatem parcelas automaticamente.</p></section>}
    {tab === 'documents' && <section className="supplier-panel"><div className="supplier-section-top"><div><h2>Documentos do fornecedor</h2><p>XML/PDF de notas, boletos, comprovantes, contratos e tabelas de preço.</p></div><button onClick={() => setDialog('document')}><Plus /> Anexar documento</button></div>{data.documents.map(d => <a className="supplier-document-row" key={d.id} href={'/api/supplier-documents/' + d.id + '/download'}><FileText /><span><b>{d.original_name}</b><small>{categories[d.category] || d.category} · {date(d.created_at)}{d.purchase_id && ' · compra #' + d.purchase_id}</small></span><small>{Math.ceil(d.bytes / 1024)} KB</small></a>)}{!data.documents.length && <p className="supplier-empty-small">Nenhum documento nesta área. Notas anteriores continuam nas respectivas compras.</p>}</section>}
    {tab === 'returns' && <section className="supplier-panel"><div className="supplier-section-top"><div><h2>Devoluções ao fornecedor</h2><p>Saída de estoque com motivo e acordo financeiro preservados.</p></div><button disabled={!data.return_items.length} onClick={() => setDialog('return')}><Package /> Registrar devolução</button></div><div className="supplier-workspace-metrics">{metric('Crédito acordado', data.credit_cents)}{metric('Dinheiro devolvido', data.refund_cents)}</div>{data.returns.data.map(r => <article className="supplier-compact-row" key={r.id}><span><b>{r.quantity} × {r.description}</b><small>{date(r.returned_on)} · {r.reason}</small></span><span>{resolutions[r.resolution as keyof typeof resolutions]}</span><strong>{money(r.value_cents)}</strong></article>)}{!data.returns.data.length && <p className="supplier-empty-small">Nenhuma devolução registrada.</p>}{pagination('returns_page', data.returns)}</section>}
    {tab === 'history' && <section className="supplier-panel"><div className="supplier-section-top"><div><h2>Ocorrências e avaliações</h2><p>Histórico de entregas, qualidade, preços e atendimento.</p></div><button onClick={() => setDialog('occurrence')}><Plus /> Registrar ocorrência</button></div>{data.occurrences.data.map(o => <article className="supplier-compact-row" key={o.id}><ClipboardList /><span><b>{o.description}</b><small>{date(o.occurred_on)} · {categories[o.category] || o.category}</small></span></article>)}{!data.occurrences.data.length && <p className="supplier-empty-small">Nenhuma ocorrência registrada.</p>}{pagination('history_page', data.occurrences)}</section>}
    {tab === 'reports' && <><div className="supplier-report-filters"><label>De<input type="date" value={from} onChange={e => { setFrom(e.target.value); setPages({}); }} /></label><label>Até<input type="date" value={to} onChange={e => { setTo(e.target.value); setPages({}); }} /></label><button onClick={() => { setFrom(''); setTo(''); setPages({}); }}>Todo o período</button></div><p className="supplier-muted">Período pela data da compra. Total comprado exclui pedidos cancelados; pagos incluem juros e descontos efetivamente registrados.</p><div className="supplier-workspace-metrics">{metric('Total comprado', data.summary.purchased_cents)}{metric('Pago', data.summary.paid_cents)}{metric('A pagar', data.summary.open_cents)}{metric('Compras', data.summary.purchases, false)}</div><div className="supplier-overview-grid"><section className="supplier-panel"><h2><TrendingUp /> Produtos mais comprados</h2>{data.most_purchased.map(p => <article className="supplier-compact-row" key={p.product_id}><span><b>{p.description}</b><small>{p.quantity} unidades pedidas</small></span><strong>{money(p.value_cents)}</strong></article>)}</section><section className="supplier-panel"><h2>Histórico de preços e lotes</h2>{data.prices.data.map(p => <article className="supplier-compact-row" key={p.id}><span><b>{p.description}</b><small>{date(p.purchased_on)} · {p.quantity} unidades · lote {p.lot || 'não informado'}</small></span><strong>{money(p.unit_cost_cents)}</strong></article>)}{pagination('prices_page', data.prices)}</section></div></>}
    {dialog && <WorkspaceForm key={dialog} kind={dialog} id={id} data={data} close={() => setDialog(undefined)} saved={() => { setDialog(undefined); setRevision(v => v + 1); onChange(); setNotice('Registro salvo com histórico preservado.'); }} />}
  </section>;
}

function WorkspaceForm({ kind, id, data, close, saved }: { kind: string; id: number; data: Workspace; close: () => void; saved: () => void }) {
  const mode = kind.split(':')[0];
  const offering = data.offerings.find(o => String(o.id) === kind.split(':')[1]);
  const [form, setForm] = useState<Record<string, any>>(() => mode === 'profile' ? Object.fromEntries(profileSections.flatMap(s => s.fields).map(f => [f.key, f.type === 'money' ? data.profile[f.key] == null ? '' : moneyInputFromCents(data.profile[f.key]) : data.profile[f.key] ?? ''])) : mode === 'offering' ? { product_id: offering?.product_id || '', supplier_code: offering?.supplier_code || '', brand: offering?.brand || '', cost_cents: offering?.cost_cents == null ? '' : moneyInputFromCents(offering.cost_cents), minimum_quantity: offering?.minimum_quantity || 1, delivery_days: offering?.delivery_days ?? '', active: offering?.active ?? true } : mode === 'return' ? { purchase_item_id: '', quantity: 1, value_cents: '', resolution: 'pending', returned_on: today(), reason: '' } : mode === 'document' ? { category: 'invoice', purchase_id: '' } : { occurred_on: today(), category: 'other', description: '', delivery_rating: '', quality_rating: '', price_rating: '', service_rating: '' });
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [confirmed, setConfirmed] = useState(false);
  const [file, setFile] = useState<File>();
  const [products, setProducts] = useState<any[]>([]), [search, setSearch] = useState('');
  const [requestKey] = useState(() => crypto.randomUUID());
  useEffect(() => {
    if (mode !== 'offering') return;
    const controller = new AbortController();
    const timer = setTimeout(() => { void supplierApi('/catalogs/products?q=' + encodeURIComponent(search), { signal: controller.signal }).then(r => setProducts(r.data || r)).catch(e => { if (!controller.signal.aborted) setError(e.message); }); }, 200);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [mode, search]);
  const change = (key: string, value: any) => { setForm(f => ({ ...f, [key]: value })); setConfirmed(false); };
  const fields = (items: Field[]) => <div className="supplier-form-grid">{items.map(f => <label key={f.key}>{f.label}{f.options ? <select aria-label={f.label} value={form[f.key] ?? ''} onChange={e => change(f.key, e.target.value)}><option value="">Não informado</option>{Object.entries(f.options).map(([v, label]) => <option value={v} key={v}>{label}</option>)}</select> : f.type === 'textarea' ? <textarea rows={3} maxLength={3000} value={form[f.key] ?? ''} onChange={e => change(f.key, e.target.value)} /> : <input type={f.type === 'money' ? 'text' : f.type || 'text'} min={f.type === 'number' ? 0 : undefined} max={f.max} step={f.key === 'discount_percent' ? '0.01' : undefined} maxLength={f.type === 'url' ? 500 : 150} value={form[f.key] ?? ''} onChange={e => change(f.key, f.type === 'money' ? maskMoneyInput(e.target.value) : e.target.value)} />}</label>)}</div>;
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (busy || !confirmed) return; setBusy(true); setError('');
    try {
      let body: any = Object.fromEntries(Object.entries(form).map(([k, v]) => [k, v === '' ? null : v]));
      const path = mode === 'profile' ? 'profile' : mode === 'offering' ? 'offerings' : mode === 'return' ? 'returns' : mode === 'document' ? 'documents' : 'occurrences';
      if (mode === 'profile') { body.minimum_order_cents = form.minimum_order_cents === '' ? null : centsFromMoneyInput(form.minimum_order_cents); body = { profile: body }; }
      if (mode === 'offering') body.cost_cents = form.cost_cents === '' ? null : centsFromMoneyInput(form.cost_cents);
      if (mode === 'return') body = { ...body, request_key: requestKey, value_cents: centsFromMoneyInput(form.value_cents) };
      if (mode === 'document') { const upload = new FormData(); upload.append('request_key', requestKey); upload.append('category', form.category); if (form.purchase_id) upload.append('purchase_id', form.purchase_id); if (file) upload.append('file', file); body = upload; }
      await supplierApi('/suppliers/' + id + '/' + path, { method: mode === 'profile' ? 'PUT' : 'POST', body: body instanceof FormData ? body : JSON.stringify(body) }); saved();
    } catch (e: any) { setError(e.message); } finally { setBusy(false); }
  };
  const title = mode === 'profile' ? 'Dados comerciais e bancários' : mode === 'offering' ? 'Produto fornecido' : mode === 'return' ? 'Devolver mercadoria' : mode === 'document' ? 'Anexar documento' : 'Ocorrência e avaliação';
  return <OrderPopup variant="editor" title={title} description="Confira os dados antes de confirmar. O histórico anterior será preservado." eyebrow="FORNECEDORES" icon={mode === 'document' ? FileText : Building2} onClose={() => { if (!busy) close(); }} closeLabel="Fechar formulário do fornecedor"><form className="supplier-form" onSubmit={submit}><div className="supplier-form-body">
    {error && <p className="supplier-error" role="alert">{error}</p>}
    {mode === 'profile' && profileSections.map(s => <section key={s.title}><h3>{s.title}</h3>{fields(s.fields)}</section>)}
    {mode === 'offering' && <section><label>Pesquisar produto<input value={search} onChange={e => setSearch(e.target.value)} /></label><label>Produto<select aria-label="Produto" disabled={!!offering} required value={form.product_id} onChange={e => change('product_id', e.target.value)}><option value="">Selecione</option>{offering && !products.some(p => p.id === offering.product_id) && <option value={offering.product_id}>{offering.name}</option>}{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{fields([{ key: 'supplier_code', label: 'Código no fornecedor' }, { key: 'brand', label: 'Marca' }, { key: 'cost_cents', label: 'Custo informado (R$)', type: 'money' }, { key: 'minimum_quantity', label: 'Quantidade mínima', type: 'number' }, { key: 'delivery_days', label: 'Entrega (dias)', type: 'number', max: 365 }])}<label className="supplier-check"><input type="checkbox" checked={!!form.active} onChange={e => change('active', e.target.checked)} /> Vínculo ativo</label></section>}
    {mode === 'return' && <section><label>Produto recebido<select aria-label="Produto recebido" required value={form.purchase_item_id} onChange={e => { const item = data.return_items.find(i => String(i.id) === e.target.value); setForm(f => ({ ...f, purchase_item_id: e.target.value, quantity: 1, value_cents: moneyInputFromCents(item?.unit_cost_cents || 0) })); setConfirmed(false); }}><option value="">Selecione a compra / produto</option>{data.return_items.map(i => <option key={i.id} value={i.id}>Compra #{i.purchase_id} · {i.description} · disponível {i.returnable_quantity}</option>)}</select></label>{fields([{ key: 'quantity', label: 'Quantidade devolvida', type: 'number' }, { key: 'value_cents', label: 'Valor total acordado (R$)', type: 'money' }, { key: 'returned_on', label: 'Data da devolução', type: 'date' }, { key: 'resolution', label: 'Acordo com fornecedor', options: resolutions }, { key: 'reason', label: 'Motivo da devolução', type: 'textarea' }])}<p>A confirmação retira unidades do estoque. Crédito ou reembolso é registrado separadamente e não altera títulos existentes.</p></section>}
    {mode === 'document' && <section>{fields([{ key: 'category', label: 'Categoria do documento', options: { invoice: 'Nota fiscal / XML', boleto: 'Boleto', receipt: 'Comprovante', contract: 'Contrato', prices: 'Tabela de preço', other: 'Outro' } }, { key: 'purchase_id', label: 'Número da compra vinculada (opcional)', type: 'number' }])}<label>Arquivo PDF, imagem ou XML<input required type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xml" onChange={e => { setFile(e.target.files?.[0]); setConfirmed(false); }} /></label><p>Até 10 MB. Arquivo privado, disponível somente para os perfis autorizados.</p></section>}
    {mode === 'occurrence' && <section>{fields([{ key: 'occurred_on', label: 'Data da ocorrência', type: 'date' }, { key: 'category', label: 'Categoria', options: { delivery: 'Entrega', quality: 'Qualidade', price: 'Preço', service: 'Atendimento', other: 'Outra' } }, { key: 'description', label: 'Descrição', type: 'textarea' }, ...['delivery', 'quality', 'price', 'service'].map((k, i) => ({ key: k + '_rating', label: ['Entrega', 'Qualidade', 'Preço', 'Atendimento'][i] + ' (opcional)', options: { '1': '1 — Ruim', '2': '2 — Regular', '3': '3 — Bom', '4': '4 — Muito bom', '5': '5 — Excelente' } }))])}</section>}
    <label className="supplier-check"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /> Conferi os dados e confirmo este registro</label>
  </div><footer className="arl-3d-footer"><button type="button" disabled={busy} onClick={close}>Cancelar</button><button className="arl-3d-primary" disabled={busy || !confirmed}>{busy ? 'Salvando…' : 'Confirmar e salvar'}</button></footer></form></OrderPopup>;
}
