import { reactPageActive } from './react-ownership';
export {};

const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'';
const api=async(url:string,options:RequestInit={})=>{const r=await fetch('/api'+url,{credentials:'same-origin',...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(csrf()?{'X-CSRF-TOKEN':csrf()}:{}) ,...options.headers}});const b=await r.json().catch(()=>({message:'Resposta inválida.'}));if(!r.ok)throw new Error(b.message||'Não foi possível concluir.');return b};
const q=<T extends Element=HTMLElement>(selector:string,root:ParentNode=document)=>root.querySelector<T>(selector);
const qa=<T extends Element=HTMLElement>(selector:string,root:ParentNode=document)=>Array.from(root.querySelectorAll<T>(selector));
const text=(el:Element|null)=>(el?.textContent||'').trim();
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const reactOrderDetailActive=()=>Boolean(document.querySelector('[data-arl-order-detail-react="1"]'));

const icons={
  whatsapp:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.8a8 8 0 0 1-11.8 7L4 20l1.2-4.1A8 8 0 1 1 20 11.8Z"/><path d="M8.8 8.7c.5 2.9 2.7 5.1 5.6 5.7"/><path d="M8.6 8.4c.3-.7.6-.7.9-.7h.5l.9 2.1c.1.3 0 .5-.2.7l-.7.8c.8 1.4 1.8 2.4 3.2 3.1l.7-.9c.2-.2.5-.3.7-.2l2 .9c.3.1.4.4.4.6 0 .7-.4 1.5-1 2-1 .8-2.3.7-3.7.1-3.1-1.3-5.5-4-6.5-7.1-.3-1-.2-1.8.3-2.4.1-.2.3-.4.5-.6Z"/></svg>',
  maps:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s6-5.3 6-11a6 6 0 1 0-12 0c0 5.7 6 11 6 11Z"/><circle cx="12" cy="10" r="2.2"/></svg>',
  camera:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h4l1.5-2h5L16 7h4v12H4Z"/><circle cx="12" cy="13" r="3.5"/></svg>',
  eye:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>',
  gear:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/><circle cx="12" cy="12" r="4"/></svg>',
  check:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.6 2.6L16.5 9"/></svg>',
  star:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9Z"/></svg>',
  instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg>',
  quote:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5h14v14H5Z"/><path d="M8 9h8M8 13h6"/></svg>',
  wallet:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h14a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h12"/><path d="M15 11h5v4h-5Z"/></svg>'
};

function sr(label:string){const span=document.createElement('span');span.className='arl-sr-only';span.textContent=label;return span}
function iconSpan(kind:keyof typeof icons){const span=document.createElement('span');span.className='arl-action-icon';span.innerHTML=icons[kind];return span}

function installStyles(){if(q('#arl-final-polish-style'))return;const style=document.createElement('style');style.id='arl-final-polish-style';style.textContent=`
.arl-sr-only{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}.arl-action-icon{display:grid;place-items:center}.arl-action-icon svg,.arl-dashboard-icon svg,.arl-external-icon svg,.arl-post-icon svg,.arl-quick-icon svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
.arl-settings-tabs{display:flex!important;flex-wrap:wrap!important;gap:6px!important;margin:8px 0 12px!important}.arl-settings-tab{width:auto!important;min-width:0!important;min-height:38px!important;padding:7px 10px!important;border-radius:9px!important;gap:6px!important}.arl-settings-tab>span:first-child{width:18px!important;min-width:18px!important;height:18px!important;font-size:12px!important}.arl-settings-tab b{font-size:11.5px!important;white-space:nowrap}.arl-settings-tab small,.arl-settings-tab>i{display:none!important}.settings-form,.arl-opening-message-panel,.arl-post-message-panel,.arl-order-settings-card,.report-settings{font-size:12.5px!important}.settings-form h2,.arl-opening-message-panel h2,.arl-post-message-panel h2{font-size:16px!important;margin:8px 0!important}.settings-form input,.settings-form select,.arl-opening-message-panel textarea,.arl-post-message-panel textarea{font-size:12.5px!important}.settings-form input,.settings-form select{min-height:38px!important}.settings-form textarea,.arl-opening-message-panel textarea,.arl-post-message-panel textarea{min-height:180px!important;line-height:1.5!important;padding:11px 12px!important}.arl-message-subnav{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 9px}.arl-message-subnav button{min-height:34px;padding:6px 10px;border:1px solid #dedde1;border-radius:9px;background:#fff;font-size:11.5px;font-weight:800;cursor:pointer}.arl-message-subnav button.active{background:#17171a;color:#fff;border-color:#17171a}.arl-post-message-panel{border:1px solid #e6e2e4;border-radius:12px;background:#fff;padding:14px;margin-bottom:10px}.arl-post-message-panel p{margin:0 0 8px;color:#747986;font-size:11.5px}.arl-post-message-panel textarea{width:100%;border:1px solid #dcdde1;border-radius:10px;resize:vertical}.arl-post-message-panel .actions{display:flex;justify-content:flex-end;gap:8px;margin-top:8px}.arl-post-message-panel button{min-height:35px;border:0;border-radius:9px;background:#c9001c;color:#fff;padding:7px 11px;font-weight:800}.arl-post-message-panel small{color:#68707b}
.client-list article.arl-client-card{min-height:0!important;padding:11px 13px!important;margin:7px 12px!important;gap:10px!important}.arl-client-avatar{width:38px!important;height:38px!important;font-size:13px!important}.arl-client-main{padding-left:48px!important;min-height:38px!important}.arl-client-card b{font-size:13.5px!important}.arl-client-card small,.arl-client-card>span{font-size:11.5px!important}.contact-links.arl-vivid-actions{display:flex!important;justify-content:flex-end!important;gap:6px!important}.arl-vivid-actions a,.arl-vivid-actions button{width:36px!important;min-width:36px!important;height:36px!important;min-height:36px!important;padding:0!important;border-radius:10px!important;display:grid!important;place-items:center!important;flex:0 0 36px!important}.arl-vivid-actions .arl-action-icon svg{width:17px;height:17px}
.dashboard-row{font-size:12px!important;min-height:48px!important}.dashboard-row.head{font-size:10.5px!important}.dashboard-row .badge{font-size:11px!important;padding:4px 8px!important}.dashboard-contact{width:34px!important;min-width:34px!important;height:34px!important;padding:0!important;border-radius:9px!important;display:grid!important;place-items:center!important;background:#effcf4!important;border:1px solid #b9e7c9!important;color:#08743a!important;text-decoration:none!important}.dashboard-address{display:inline-flex!important;align-items:center!important;gap:6px!important;font-size:11.5px!important}.arl-dashboard-icon{display:grid;place-items:center}.dashboard-row .arl-view-order{min-height:32px!important;padding:5px 9px!important;font-size:11px!important;border-radius:8px!important}
.title:has(h1[id]),.title{row-gap:5px}.status-picker{max-width:165px!important}.status-picker select{min-height:34px!important;font-size:12px!important;padding:5px 9px!important}.detail-grid{gap:9px!important}.detail-grid>section{padding:11px 13px!important;border-radius:12px!important;min-height:0!important}.detail-grid>section h2{font-size:13.5px!important;margin:0 0 7px!important}.detail-grid>section p,.detail-grid>section small{font-size:11.5px!important;line-height:1.45!important}.external-actions{display:flex!important;gap:7px!important;justify-content:flex-start!important;margin:7px 0 9px!important}.external-actions>a,.external-actions>button,.external-actions>label{width:40px!important;min-width:40px!important;height:40px!important;min-height:40px!important;padding:0!important;border-radius:12px!important;display:grid!important;place-items:center!important;position:relative!important}.external-actions input[type=file]{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important}.arl-external-icon{display:grid;place-items:center}.external-actions [data-arl-finalize]{background:#effcf4!important;border-color:#9fdab5!important;color:#08743a!important}.arl-order-quick-actions{display:flex;gap:7px;flex-wrap:wrap;margin:6px 0 10px}.arl-order-quick-actions button{min-height:35px;border:1px solid #dfdce0;border-radius:9px;background:#fff;padding:6px 10px;font-size:11.5px;font-weight:800;display:inline-flex;align-items:center;gap:6px;cursor:pointer}.arl-order-quick-actions button.primary{background:#c9001c;color:#fff;border-color:#c9001c}.arl-quick-icon{display:grid;place-items:center}.detail-grid button[data-arl-quick-source]{display:none!important}.arl-payment-empty{min-height:0!important;padding:0!important;border:0!important;box-shadow:none!important;background:transparent!important}.arl-payment-empty>:not(.modal){display:none!important}.arl-payment-compact .section-title p{display:none!important}.arl-payment-compact .finance-cards{grid-template-columns:repeat(3,minmax(110px,1fr))!important;gap:6px!important}.arl-payment-compact .finance-cards article{padding:8px 10px!important}.arl-payment-compact .finance-cards small{font-size:10px!important}.arl-payment-compact .finance-cards strong{font-size:13px!important}.arl-photo-choice{position:fixed;inset:0;z-index:260;background:#0008;display:grid;place-items:center;padding:16px}.arl-photo-choice>div{width:min(330px,100%);background:#fff;border-radius:16px;padding:18px;display:grid;gap:8px;box-shadow:0 24px 70px #0004}.arl-photo-choice h3{margin:0 0 4px;font-size:17px}.arl-photo-choice button{min-height:39px;border:1px solid #dedde1;border-radius:9px;background:#fff;font-weight:800}.arl-photo-choice button.primary{background:#c9001c;color:#fff;border-color:#c9001c}
.arl-post-sale-editor{display:none!important}.arl-post-sale-panel{gap:7px!important}.arl-post-sale-panel article{min-height:72px!important;padding:10px 12px!important;gap:8px!important}.arl-post-sale-panel article b,.arl-post-sale-panel article strong{font-size:12px!important}.arl-post-sale-panel article .post-action,.arl-post-sale-panel article .sent{width:40px!important;min-width:40px!important;height:40px!important;min-height:40px!important;padding:0!important;border-radius:11px!important;display:grid!important;place-items:center!important;font-size:0!important}.arl-post-icon{display:grid;place-items:center}.arl-post-google{background:#fff8dd!important;color:#8a6100!important;border-color:#eed27a!important}.arl-post-instagram{background:#f8efff!important;color:#7b26a8!important;border-color:#dcc1ec!important}.arl-post-sale-panel .sent{opacity:.65!important}.arl-post-toolbar{padding:7px!important;gap:7px!important}.arl-post-toolbar input{min-height:36px!important;font-size:12px!important}.arl-post-toolbar button{min-height:34px!important;padding:5px 8px!important;font-size:11px!important}
@media(max-width:760px){.arl-settings-tabs{overflow-x:auto;flex-wrap:nowrap!important;padding-bottom:3px}.arl-settings-tab{flex:0 0 auto}.detail-grid{grid-template-columns:1fr!important}.arl-payment-compact .finance-cards{grid-template-columns:1fr!important}.dashboard-row{font-size:11.5px!important}}
`;document.head.append(style)}

function compactSettingsScope(){ if (reactPageActive('settings')) return;const settings=qa<HTMLHeadingElement>('h1').some(h=>text(h)==='Configurações');if(!settings)qa<HTMLElement>('.arl-settings-tabs,.arl-opening-message-panel,.arl-finance-settings-note,.arl-message-subnav,.arl-post-message-panel,.arl-order-subtabs,.arl-document-subtabs').forEach(el=>el.remove())}

let messageSettingsLoading=false,messageSettings:any=null;
async function ensureMessageSubtabs(){ if (reactPageActive('settings')) return;if(!qa<HTMLHeadingElement>('h1').some(h=>text(h)==='Configurações'))return;const opening=q<HTMLElement>('.arl-opening-message-panel');if(!opening)return;let nav=q<HTMLElement>('.arl-message-subnav');if(!nav){nav=document.createElement('div');nav.className='arl-message-subnav';nav.dataset.arlSettingsSection='messages';nav.innerHTML='<button type="button" data-msg-tab="opening">Abertura da OS</button><button type="button" data-msg-tab="google">Avaliação Google</button><button type="button" data-msg-tab="instagram">Instagram</button>';opening.before(nav);for(const [id,title,key,hint] of [['google','Avaliação Google','post_sale_google','Mensagem enviada pelo ícone de estrela no Pós-Venda.'],['instagram','Instagram','post_sale_instagram','Mensagem enviada pelo ícone do Instagram no Pós-Venda.']] as const){const panel=document.createElement('section');panel.className='arl-post-message-panel';panel.dataset.arlSettingsSection='messages';panel.dataset.msgPanel=id;panel.innerHTML=`<h2>${title}</h2><p>${hint}</p><textarea data-key="${key}"></textarea><div class="actions"><small data-status></small><button type="button" data-save>Salvar mensagem</button></div>`;opening.insertAdjacentElement('afterend',panel);panel.querySelector<HTMLButtonElement>('[data-save]')!.addEventListener('click',async()=>{const area=panel.querySelector<HTMLTextAreaElement>('textarea')!,status=panel.querySelector<HTMLElement>('[data-status]')!;status.textContent='Salvando…';try{messageSettings=await api('/post-sales/settings',{method:'PUT',body:JSON.stringify({[key]:area.value})});status.textContent='Salvo.'}catch(e){status.textContent=e instanceof Error?e.message:'Erro ao salvar.'}})}qa<HTMLButtonElement>('[data-msg-tab]',nav).forEach(button=>button.addEventListener('click',()=>{document.documentElement.dataset.arlMessageSubtab=button.dataset.msgTab||'opening';syncMessageVisibility()}))}if(!document.documentElement.dataset.arlMessageSubtab)document.documentElement.dataset.arlMessageSubtab='opening';if(!messageSettings&&!messageSettingsLoading){messageSettingsLoading=true;try{messageSettings=await api('/post-sales/settings');qa<HTMLTextAreaElement>('.arl-post-message-panel textarea').forEach(area=>{area.value=messageSettings?.[area.dataset.key||'']||''})}finally{messageSettingsLoading=false}}syncMessageVisibility()}
function syncMessageVisibility(){ if (reactPageActive('settings')) return;const topActive=q<HTMLButtonElement>('.arl-settings-tab.active')?.dataset.section==='messages',active=document.documentElement.dataset.arlMessageSubtab||'opening',opening=q<HTMLElement>('.arl-opening-message-panel');if(opening)opening.hidden=!topActive||active!=='opening';qa<HTMLElement>('.arl-post-message-panel').forEach(panel=>panel.hidden=!topActive||panel.dataset.msgPanel!==active);qa<HTMLButtonElement>('.arl-message-subnav [data-msg-tab]').forEach(button=>button.classList.toggle('active',button.dataset.msgTab===active));const nav=q<HTMLElement>('.arl-message-subnav');if(nav)nav.hidden=!topActive}

function iconifyClientActions(){if(q('[data-arl-clients-react="1"]'))return;qa<HTMLElement>('.client-list .contact-links a,.client-list .contact-links button').forEach(action=>{if(action.classList.contains('arl-client-delete')||action.dataset.arlIconified==='1')return;const label=text(action);let kind:keyof typeof icons|undefined,title='';if(/WhatsApp/i.test(label)){kind='whatsapp';title='Abrir WhatsApp'}else if(/^Maps$/i.test(label)){kind='maps';title='Abrir Google Maps'}else if(/Visualizar/i.test(label)){kind='eye';title='Visualizar cliente'}else if(/^Editar$/i.test(label)){kind='gear';title='Editar cliente'}if(!kind)return;action.dataset.arlIconified='1';action.replaceChildren(iconSpan(kind),sr(title));action.setAttribute('aria-label',title);action.setAttribute('title',title)})}

function polishDashboard(){ if (reactPageActive('dashboard')) return;qa<HTMLAnchorElement>('.dashboard-contact').forEach(link=>{if(link.dataset.arlIconified==='1')return;const phone=text(link).replace(/[☎●◆◉]/g,'').trim();link.dataset.arlIconified='1';const icon=document.createElement('span');icon.className='arl-dashboard-icon';icon.innerHTML=icons.whatsapp;link.replaceChildren(icon,sr(`Abrir WhatsApp${phone?` ${phone}`:''}`));link.setAttribute('aria-label',`Abrir WhatsApp${phone?` ${phone}`:''}`);link.title='WhatsApp'});qa<HTMLAnchorElement>('.dashboard-address').forEach(link=>{if(link.dataset.arlIconified==='1')return;const location=text(link).replace(/^[●◆\s]+/,'').trim();link.dataset.arlIconified='1';const icon=document.createElement('span');icon.className='arl-dashboard-icon';icon.innerHTML=icons.maps;link.replaceChildren(icon,document.createTextNode(location));link.setAttribute('aria-label',`Abrir no Google Maps: ${location}`);link.title='Google Maps'})}

function externalIcon(el:HTMLElement,kind:keyof typeof icons,label:string){if(el.dataset.arlIconified==='1')return;el.dataset.arlIconified='1';const input=el.querySelector('input');el.replaceChildren();const icon=document.createElement('span');icon.className='arl-external-icon';icon.innerHTML=icons[kind];el.append(icon,sr(label));if(input)el.append(input);el.setAttribute('aria-label',label);el.setAttribute('title',label)}
function showPhotoChoice(input:HTMLInputElement){q('.arl-photo-choice')?.remove();const overlay=document.createElement('div');overlay.className='arl-photo-choice';overlay.innerHTML='<div><h3>Adicionar foto</h3><button type="button" class="primary" data-upload>Enviar arquivo</button><button type="button" data-camera>Usar câmera / webcam</button><button type="button" data-cancel>Cancelar</button></div>';document.body.append(overlay);overlay.querySelector('[data-cancel]')?.addEventListener('click',()=>overlay.remove());overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove()});overlay.querySelector('[data-upload]')?.addEventListener('click',()=>{overlay.remove();input.click()});overlay.querySelector('[data-camera]')?.addEventListener('click',()=>{overlay.remove();const camera=q<HTMLButtonElement>('.detail-grid .arl-camera-button');if(camera)camera.dispatchEvent(new MouseEvent('click',{bubbles:true}));else input.click()})}
function polishExternalActions(){const actions=q<HTMLElement>('.external-actions');if(!actions)return;qa<HTMLButtonElement>('button',actions).filter(b=>b.id==='external-status-action'||text(b)==='Status').forEach(b=>b.remove());const anchors=qa<HTMLAnchorElement>('a',actions);const wa=anchors.find(a=>/WhatsApp/i.test(text(a))||a.href.includes('wa.me'));if(wa)externalIcon(wa,'whatsapp','WhatsApp');const maps=anchors.find(a=>/^Maps$/i.test(text(a))||a.href.includes('google'));if(maps)externalIcon(maps,'maps','Google Maps');const photo=qa<HTMLElement>('label',actions).find(l=>text(l).includes('Foto'));if(photo){const input=photo.querySelector<HTMLInputElement>('input[type=file]');externalIcon(photo,'camera','Adicionar foto');if(input&&photo.dataset.arlChoiceBound!=='1'){photo.dataset.arlChoiceBound='1';photo.addEventListener('click',e=>{if(e.target===input)return;e.preventDefault();e.stopPropagation();showPhotoChoice(input)},true)}}const finish=qa<HTMLButtonElement>('button',actions).find(b=>/Finalizar/i.test(text(b)));if(finish){externalIcon(finish,'check','Finalizar OS');finish.dataset.arlFinalize='1'}}

const orderSection=(name:string)=>qa<HTMLElement>('.detail-grid>section').find(section=>text(section.querySelector('h2'))===name);
function quickButton(bar:HTMLElement,key:string,label:string,kind:keyof typeof icons,source:HTMLButtonElement,primary=false){let button=bar.querySelector<HTMLButtonElement>(`[data-quick="${key}"]`);if(!button){button=document.createElement('button');button.type='button';button.dataset.quick=key;button.innerHTML=`<span class="arl-quick-icon">${icons[kind]}</span><span>${label}</span>`;if(primary)button.classList.add('primary');button.addEventListener('click',()=>source.dispatchEvent(new MouseEvent('click',{bubbles:true})));bar.append(button)}button.disabled=source.disabled}
function polishOrderDetail(){if(reactOrderDetailActive())return;const heading=qa<HTMLHeadingElement>('h1').find(h=>text(h).startsWith('OS #'));if(!heading)return;polishExternalActions();const title=heading.closest<HTMLElement>('.title');let bar=q<HTMLElement>('.arl-order-quick-actions');if(!bar&&title){bar=document.createElement('div');bar.className='arl-order-quick-actions';const external=q<HTMLElement>('.external-actions');if(external)external.insertAdjacentElement('afterend',bar);else title.insertAdjacentElement('afterend',bar)}if(bar){const budget=orderSection('Orçamentos'),budgetSource=q<HTMLButtonElement>('button[data-arl-quick-source="budget"]',budget||document);if(budgetSource)quickButton(bar,'budget','Gerar orçamento','quote',budgetSource);const payment=orderSection('Pagamento'),paySource=q<HTMLButtonElement>('button[data-arl-quick-source="payment"]',payment||document);if(paySource)quickButton(bar,'payment',text(paySource).includes('novo')?'Registrar novo pagamento':'Registrar pagamento','wallet',paySource,true);else bar.querySelector('[data-quick="payment"]')?.remove();if(!budgetSource)bar.querySelector('[data-quick="budget"]')?.remove()}const payment=orderSection('Pagamento');if(payment){const hasTransactions=!!payment.querySelector('.transaction'),empty=text(payment).includes('Pagamento ainda não registrado');payment.classList.toggle('arl-payment-empty',empty&&!hasTransactions);payment.classList.toggle('arl-payment-compact',!empty||hasTransactions)}}

function postIcon(element:HTMLElement,kind:'google'|'instagram',sent:boolean){const label=kind==='google'?'Enviar avaliação Google':'Enviar Instagram';if(element.dataset.arlPostKind===kind&&element.dataset.arlSent===String(sent))return;element.dataset.arlPostKind=kind;element.dataset.arlSent=String(sent);element.classList.toggle('arl-post-google',kind==='google');element.classList.toggle('arl-post-instagram',kind==='instagram');element.replaceChildren();const icon=document.createElement('span');icon.className='arl-post-icon';icon.innerHTML=kind==='google'?icons.star:icons.instagram;element.append(icon,sr(sent?`${label} — enviado`:label));element.setAttribute('aria-label',sent?`${label} — enviado`:label);element.setAttribute('title',sent?`${label} — enviado`:label)}
function polishPostSale(){const panel=q<HTMLElement>('.post-sale');if(!panel)return;q<HTMLElement>('.arl-post-sale-editor')?.setAttribute('aria-hidden','true');qa<HTMLElement>('article',panel).forEach(article=>{let actions=Array.from(article.children).filter((el):el is HTMLElement=>el instanceof HTMLElement&&(el.matches('a.post-action')||el.matches('button.sent')));if(article.dataset.arlFollowupRemoved!=='1'&&actions.length>=3){actions[0].remove();article.dataset.arlFollowupRemoved='1';actions=actions.slice(1)}if(actions.length>=2){postIcon(actions[0],'google',actions[0].matches('button.sent'));postIcon(actions[1],'instagram',actions[1].matches('button.sent'))}})}

function run(){installStyles();compactSettingsScope();void ensureMessageSubtabs();syncMessageVisibility();iconifyClientActions();polishDashboard();polishOrderDetail();polishPostSale()}
let queued=false;const queue=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;run()})};new MutationObserver(queue).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',queue,true);document.addEventListener('DOMContentLoaded',queue);window.addEventListener('arl:order-detail',queue);queue();
