import { expect, test } from '@playwright/test';
import { api, login, uniqueDocument, validServiceItem } from './helpers';

test('orçamento usa link protegido, download e confirmação humana de envio', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await login(page);
  const name = `Cliente Orçamento ${Date.now()}`;
  const client = await api(page, '/clients', 'POST', { name, document: uniqueDocument(), phone: '35999991234', street: 'Rua do Orçamento' });
  expect(client.status).toBe(201);
  const equipment = await api(page, '/catalogs/equipment');
  const order = await api(page, '/orders', 'POST', {
    client_id: client.body.id, equipment_type_id: equipment.body[0].id,
    equipment_description: 'Notebook Dell Inspiron', equipment_details: 'Carregador original e mochila',
    attendance_type: 'bench', reported_problem: 'Não liga ao conectar o carregador.', intake_condition: 'Pequeno risco na tampa.', checklist: [],
  });
  expect(order.status).toBe(201);
  await page.goto(`/orders/${order.body.id}`);
  const root = page.locator('[data-arl-unified-order-editor-host="1"]');
  await root.getByRole('button', { name: 'Editar', exact: true }).click();
  const editor = page.locator('.arl-editor-refined');
  await expect(editor.getByRole('heading', { name: 'Equipamento e acesso' })).toBeVisible();
  await expect(editor.getByLabel('Estado físico na entrada')).toHaveValue('Pequeno risco na tampa.');
  await page.screenshot({ path: 'output/ficha-orcamento/ficha-edicao.png', fullPage: true });
  await editor.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await root.locator('[data-order-action="budget"]').click();
  const form = page.getByRole('dialog', { name: 'Gerar orçamento' });
  await expect(form).toBeVisible();
  await form.getByLabel('Diagnóstico').fill('Falha no circuito de alimentação.');
  await form.getByLabel('Serviço proposto').fill('Reparo do circuito e testes de funcionamento.');
  await form.getByLabel('Observação (opcional)').fill('Execução após aprovação do cliente.');
  const item = await validServiceItem(page);
  await form.getByLabel('Buscar serviço ou produto para o orçamento').fill(item.description);
  await form.getByRole('button', { name: `Adicionar ${item.description}`, exact: true }).click();
  await page.setViewportSize({ width: 1280, height: 720 });
  const saveButton = form.getByRole('button', { name: 'Salvar e gerar PDF' });
  await expect(saveButton).toBeVisible();
  const saveBounds = await saveButton.boundingBox();
  expect(saveBounds!.y + saveBounds!.height).toBeLessThanOrEqual(720);
  await page.screenshot({ path: 'output/ficha-orcamento/modal-orcamento-720.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'output/ficha-orcamento/modal-orcamento.png' });
  await form.getByRole('button', { name: 'Salvar e gerar PDF' }).click();
  const prompt = page.getByRole('dialog', { name: 'Enviar orçamento ao cliente' });
  await expect(prompt).toBeVisible();
  await prompt.getByRole('button', { name: 'Agora não' }).click();
  const row = page.locator('.arl-budget-card').filter({ hasText: 'Revisão 1' });
  await expect(row.getByText('Rascunho', { exact: true })).toBeVisible();
  await expect(row.locator('.arl-budget-compact-actions').getByRole('button')).toHaveCount(2);
  await expect(row.getByRole('link', { name: 'Baixar PDF' })).toBeVisible();
  await row.scrollIntoViewIfNeeded();
  await row.screenshot({ path: 'output/ficha-orcamento/acoes-orcamento.png' });
  const downloadPromise = page.waitForEvent('download');
  await row.getByRole('link', { name: 'Baixar PDF' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toContain('Orcamento-OS-');
  await download.saveAs('output/ficha-orcamento/orcamento.pdf');
  await page.context().route('https://wa.me/**', (route) => route.fulfill({ contentType: 'text/html', body: '<p>WhatsApp teste</p>' }));
  const shareResponse = page.waitForResponse((response) => response.url().endsWith(`/budgets/1/share`) && response.request().method() === 'POST');
  const popupPromise = page.waitForEvent('popup');
  await row.getByRole('button', { name: 'Enviar Orçamento', exact: true }).click();
  const share = await (await shareResponse).json();
  const popup = await popupPromise;
  await expect(prompt.getByRole('heading', { name: 'Confirme o envio' })).toBeVisible();
  await expect(popup).toHaveURL(share.whatsapp_url);
  const message = new URL(share.whatsapp_url).searchParams.get('text');
  expect(message).toBe(`Olá, ${name}. Tudo bem?\n\nGostariamos de informar que o seu orçamento já está disponível. Você pode visualizá-lo através do seguinte link:\n\n${share.url}\n\nAssim que analisar as condições, por favor, entre em contato conosco por este WhatsApp para confirmar o agendamento/execução do serviço ou esclarecer qualquer dúvida.\n\nAgradecemos a preferência e aguardamos o seu retorno.\n\nAtenciosamente\n*Arl Informática*`);
  expect((await api(page, `/orders/${order.body.id}/budgets`)).body[0].status).toBe('draft');
  const withoutCsrf = await page.context().request.post(new URL(`/api/orders/${order.body.id}/budgets/1/share`, share.url).toString(), { headers: { Accept: 'application/json' } });
  expect(withoutCsrf.status()).toBe(419);
  expect((await withoutCsrf.json()).code).toBe('SESSION_EXPIRED');
  const guest = await page.context().browser()!.newContext();
  const pdf = await guest.request.get(share.url);
  expect(pdf.status()).toBe(200);
  expect(pdf.headers()['content-type']).toContain('application/pdf');
  expect((await pdf.body()).subarray(0, 5).toString()).toBe('%PDF-');
  expect((await guest.request.get(share.url.replace(/\/share\/budget\/.*/, `/api/orders/${order.body.id}/budgets/1/pdf`), { headers: { Accept: 'application/json' } })).status()).toBe(401);
  await prompt.getByRole('button', { name: 'Mensagem enviada' }).click();
  await expect(row.getByText('Enviado', { exact: true })).toBeVisible();
  await row.getByLabel('Situação do orçamento Revisão 1').selectOption('approved');
  await expect(row.locator('.arl-budget-status-approved')).toBeVisible();
  await expect(row.getByLabel('Situação do orçamento Revisão 1')).toHaveCount(0);
  await popup.close();
  await guest.close();
  await page.evaluate(() => { window.open = () => null; });
  await row.getByRole('button', { name: 'Enviar Orçamento', exact: true }).click();
  await expect(prompt.getByRole('link', { name: 'Abrir WhatsApp' })).toHaveAttribute('href', /^https:\/\/wa\.me\/5535999991234\?text=/);
  await expect(prompt.getByRole('button', { name: 'Mensagem enviada' })).toHaveCount(0);
  await prompt.getByRole('button', { name: 'Agora não' }).click();
  expect((await api(page, `/orders/${order.body.id}/budgets`)).body[0].status).toBe('approved');
});
