import { test, expect } from '@playwright/test';
import { login } from './helpers';

test('cartões: galeria, edição sem perda da imagem, upload e enquadramento', async ({ page }) => {
  await login(page);
  await page.getByRole('button', { name: 'Controle de Gasto', exact: true }).click();
  await page.getByRole('tab', { name: 'Instituições', exact: true }).click();
  await page.getByRole('button', { name: 'Cadastrar instituição', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Cadastrar instituição', exact: true });
  await expect(dialog.getByRole('button', { name: /^Selecionar cartão / })).toHaveCount(12);
  await dialog.getByLabel('Buscar banco na galeria').fill('itau');
  await expect(dialog.getByRole('button', { name: /^Selecionar cartão / })).toHaveCount(2);
  await dialog.getByLabel('Buscar banco na galeria').fill('nubank');
  await dialog.getByRole('button', { name: 'Selecionar cartão Nubank', exact: true }).click();
  const name = 'Cartão visual ' + Date.now();
  await dialog.getByLabel('Nome', { exact: true }).fill(name);
  await dialog.locator('.cg-dialog-body').evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: 'output/cartoes/galeria-desktop.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Salvar', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  const institution = page.locator('.cg-institution').filter({ hasText: name });
  await expect(institution.locator('.cg-card-wordmark')).toHaveText('nu');
  await institution.getByRole('button', { name: 'Editar instituição ' + name }).click();
  const edit = page.getByRole('dialog', { name: 'Editar instituição', exact: true });
  await edit.getByRole('button', { name: 'Minha imagem', exact: true }).click();
  await edit.getByLabel('Imagem do cartão', { exact: true }).setInputFiles('public/arl-assets/expense-cards/bradesco-neo.png');
  await expect(edit.getByRole('button', { name: 'Salvar', exact: true })).toBeDisabled();
  await expect(edit.getByRole('button', { name: 'Aplicar enquadramento' })).toBeEnabled();
  await edit.getByRole('button', { name: 'Aplicar enquadramento' }).click();
  await expect(edit.getByRole('button', { name: 'Salvar', exact: true })).toBeEnabled();
  await edit.getByRole('button', { name: 'Salvar', exact: true }).click();
  await edit.getByRole('button', { name: 'Confirmar alteração', exact: true }).click();
  await expect(edit).not.toBeVisible();
  const image = institution.locator('.cg-card-art img');
  await expect(image).toBeVisible();
  const original = await image.getAttribute('src');
  expect(original).toContain('/api/expense-control/institutions/');
  await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth === 856)).toBe(true);
  await institution.getByRole('button', { name: 'Editar instituição ' + name }).click();
  await edit.getByLabel('Dia padrão de vencimento').fill('17');
  await edit.getByRole('button', { name: 'Salvar', exact: true }).click();
  await edit.getByRole('button', { name: 'Confirmar alteração', exact: true }).click();
  await expect(edit).not.toBeVisible();
  await expect(institution.getByText('Vencimento padrão · dia 17', { exact: true })).toBeVisible();
  await expect(image).toHaveAttribute('src', original!);
  await page.screenshot({ path: 'output/cartoes/instituicoes-desktop.png', fullPage: true });
});

test('cartões: galeria utilizável no celular e botão salvar acessível', async ({ page }) => {
  await login(page);
  await page.getByRole('button', { name: 'Controle de Gasto', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => localStorage.setItem('arl-layout-mode', 'mobile'));
  await page.reload();
  await page.getByRole('tab', { name: 'Instituições', exact: true }).click();
  await page.getByRole('button', { name: 'Cadastrar instituição', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Cadastrar instituição', exact: true });
  await dialog.getByLabel('Buscar banco na galeria').fill('mercado');
  await dialog.getByRole('button', { name: 'Selecionar cartão Mercado Pago', exact: true }).click();
  await expect(dialog.getByLabel('Nome', { exact: true })).toHaveValue('Mercado Pago');
  await expect(dialog.getByRole('button', { name: 'Salvar', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: 'output/cartoes/galeria-mobile.png', fullPage: true });
});
