import { test, expect } from '@playwright/test';
import { api, login } from './helpers';
import path from 'node:path';

test('foto: OCR real local, revisão e cadastro das parcelas em lote', async ({ page }) => {
  test.setTimeout(180000);
  await login(page);
  const stamp = Date.now();
  const bank = (await api(page, '/expense-control/catalogs/institutions', 'POST', { name: 'Foto ' + stamp, active: true, due_day: 12, color: '#c9002c' })).body;
  const type = (await api(page, '/expense-control/catalogs/types', 'POST', { name: 'Crédito foto ' + stamp, active: true })).body;
  const external: string[] = [];
  page.on('request', request => { if (/tesseract|traineddata|wasm/.test(request.url()) && new URL(request.url()).origin !== new URL(page.url()).origin) external.push(request.url()); });
  await page.getByRole('button', { name: 'Controle de Gasto', exact: true }).click();
  await page.getByRole('button', { name: 'Cadastrar por foto', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Foto da fatura', { exact: true }).setInputFiles(path.resolve('tests/fixtures/expense-invoice.png'));
  await page.screenshot({ path: 'output/foto/upload-desktop.png', fullPage: true });
  await dialog.getByRole('button', { name: 'Ler compras', exact: true }).click();
  await expect(dialog.getByRole('heading', { name: 'Confira as compras reconhecidas' })).toBeVisible({ timeout: 120000 });
  await expect(dialog.locator('.cg-photo-row')).toHaveCount(2);
  await expect(dialog.getByLabel('Nome da compra 1', { exact: true })).toHaveValue('LOJA GELADEIRA');
  await expect(dialog.getByLabel('Valor da parcela da compra 1', { exact: true })).toHaveValue('120,50');
  await expect(dialog.getByLabel('Parcela atual da compra 1', { exact: true })).toHaveValue('3');
  await expect(dialog.getByLabel('Total de parcelas da compra 1', { exact: true })).toHaveValue('10');
  await expect(dialog.getByRole('button', { name: 'Salvar 2 compras' })).toBeDisabled();
  await dialog.getByRole('combobox', { name: 'Selecionar cartão geral', exact: true }).selectOption(String(bank.id));
  await dialog.getByRole('combobox', { name: 'Selecionar tipo de dívida', exact: true }).selectOption(String(type.id));
  await dialog.getByRole('combobox', { name: 'Responsável padrão', exact: true }).selectOption('shared');
  await dialog.getByLabel('Mês desta fatura').fill('2026-10');
  await dialog.getByLabel('Conferi a compra 1', { exact: true }).check();
  await dialog.getByLabel('Conferi a compra 2', { exact: true }).check();
  await expect(dialog.getByRole('button', { name: 'Salvar 2 compras' })).toBeEnabled();
  await dialog.getByLabel('Valor da parcela da compra 1', { exact: true }).fill('12051');
  await expect(dialog.getByLabel('Conferi a compra 1', { exact: true })).not.toBeChecked();
  await dialog.getByLabel('Conferi a compra 1', { exact: true }).check();
  await dialog.locator('.cg-dialog-body').evaluate(e => { e.scrollTop = 0; });
  await dialog.locator('.cg-photo-review-list').evaluate(e => { e.scrollTop = 0; });
  await page.screenshot({ path: 'output/foto/revisao-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(dialog.getByRole('button', { name: 'Salvar 2 compras' })).toBeVisible();
  expect(await dialog.evaluate(e => e.scrollWidth <= e.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: 'output/foto/revisao-mobile.png', fullPage: true });
  const response = page.waitForResponse(r => r.url().endsWith('/api/expense-control/photo-imports') && r.request().method() === 'POST');
  await dialog.getByRole('button', { name: 'Salvar 2 compras' }).click();
  const saved = await response;
  expect(saved.status()).toBe(201);
  const body = await saved.json();
  expect(JSON.stringify(saved.request().postDataJSON())).not.toMatch(/data:image|source_line|traineddata/);
  await expect(dialog).not.toBeVisible();
  const debt = (await api(page, '/expense-control/debts/' + body.debt_ids[0])).body;
  expect(debt.installments).toHaveLength(8);
  expect(debt.installments[0]).toMatchObject({ number: 3, amount_cents: 12051, month_on: '2026-10-01' });
  expect(external).toEqual([]);
});

test('foto: arquivo inválido e cancelamento não cadastram compras', async ({ page }) => {
  await login(page);
  let saves = 0;
  page.on('request', r => { if (r.url().endsWith('/photo-imports') && r.method() === 'POST') saves++; });
  await page.getByRole('button', { name: 'Controle de Gasto', exact: true }).click();
  await page.getByRole('button', { name: 'Cadastrar por foto', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Foto da fatura', { exact: true }).setInputFiles({ name: 'arquivo.txt', mimeType: 'text/plain', buffer: Buffer.from('não é uma foto') });
  await expect(dialog.getByRole('alert')).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Ler compras', exact: true })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: 'Cadastrar por foto', exact: true }).click();
  await dialog.getByLabel('Foto da fatura', { exact: true }).setInputFiles(path.resolve('tests/fixtures/expense-invoice.png'));
  await dialog.getByRole('button', { name: 'Ler compras', exact: true }).click();
  await dialog.getByRole('button', { name: 'Cancelar leitura', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: 'Nova dívida', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Cadastrar nova dívida' })).toBeVisible();
  expect(saves).toBe(0);
});
