import { test, expect, type Page } from '@playwright/test';
import { api, login } from './helpers';

async function fixture(page: Page) {
  await login(page);
  const name = 'Banco histórico ' + Date.now();
  const bank = (await api(page, '/expense-control/catalogs/institutions', 'POST', { name, active: true, due_day: 10, color: '#2273b9' })).body;
  const kind = (await api(page, '/expense-control/catalogs/types', 'POST', { name: 'Histórico crédito ' + Date.now(), active: true })).body;
  const month = new Date().toLocaleDateString('sv-SE').slice(0, 7);
  const debt = await api(page, '/expense-control/debts', 'POST', { request_key: crypto.randomUUID(), institution_id: bank.id, type_id: kind.id, name: 'Compra histórica ' + Date.now(), recurrence: 'installments', responsibility: 'shared', percent_one: 50, amount_cents: 10000, installment_count: 3, first_number: 1, start_month: month, due_day: 10 });
  expect(debt.status).toBe(201);
  const operation = await api(page, '/expense-control/operations', 'POST', { request_key: crypto.randomUUID(), installment_ids: debt.body.installments.map((i: any) => i.id), kind: 'advance', target: 'both', paid_by: 2, occurred_on: new Date().toLocaleDateString('sv-SE') });
  expect(operation.status).toBe(201);
  expect((await api(page, '/expense-control/debts', 'POST', { request_key: crypto.randomUUID(), institution_id: bank.id, type_id: kind.id, name: 'Compra pendente ' + Date.now(), recurrence: 'installments', responsibility: 'shared', percent_one: 50, amount_cents: 15000, installment_count: 3, first_number: 1, start_month: month, due_day: 10 })).status).toBe(201);
  const last = new Date(month + '-01T12:00:00'); last.setMonth(last.getMonth() + 2);
  return { bank, kind, debt: debt.body, month, end: last.toLocaleDateString('sv-SE').slice(0, 7) };
}

test('histórico desktop: consulta real, divisão individual e quitada compacta com pagador', async ({ page }) => {
  const data = await fixture(page);
  await page.goto('/expense-control');
  await page.getByRole('tab', { name: 'Projeção', exact: true }).click();
  await expect(page.locator('.cg-projection-list')).toBeVisible();
  await page.getByRole('button', { name: 'Histórico de gastos', exact: true }).click();
  await page.getByLabel('Mês inicial do histórico').fill(data.month);
  await page.getByLabel('Mês final do histórico').fill(data.end);
  await page.getByLabel('Responsável no histórico').selectOption('one');
  await page.getByRole('button', { name: 'OK', exact: true }).click();
  const report = (await api(page, '/expense-control/spending-history?start=' + data.month + '&end=' + data.end + '&person=one')).body;
  const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value / 100);
  await expect(page.locator('.cg-history-totals article').first()).toContainText(money(report.total_cents));
  await expect(page.locator('.cg-history-month')).toHaveCount(3);
  await expect(page.locator('.cg-history-month').nth(1)).toContainText('Sem mudança');
  await expect(page.locator('.cg-history-totals article').last()).toContainText(money(report.advance_cents));
  await page.screenshot({ path: 'output/controle-gasto/historico-desktop.png', fullPage: true });
  await page.getByRole('tab', { name: 'Quitadas', exact: true }).click();
  await page.getByLabel('Pesquisar compra ou instituição').fill(data.debt.debt.name);
  const row = page.locator('.cg-settled-row').filter({ hasText: data.debt.debt.name });
  await expect(row).toContainText('Pago por Carol');
  await expect(row).toContainText('300,00');
  await expect(page.locator('.cg-table-wrap')).toHaveCount(0);
  await page.screenshot({ path: 'output/controle-gasto/quitadas-compactas-desktop.png', fullPage: true });
});

test('mobile documento: projeção sem sobreposição, filtros recolhidos, lista sem imagens e ícones iguais', async ({ page }) => {
  const data = await fixture(page);
  await page.evaluate(() => localStorage.setItem('arl-layout-mode', 'mobile'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/expense-control');
  await expect(page.locator('.cg-mobile')).toBeVisible();
  await page.getByRole('tab', { name: 'Gastos', exact: true }).click();
  await expect(page.getByLabel('Pesquisar compra ou instituição')).not.toBeVisible();
  await page.getByRole('button', { name: 'Lista', exact: true }).click();
  const row = page.locator('.cg-bank-list-row').filter({ hasText: data.bank.name });
  await expect(row).toBeVisible();
  await expect(row.locator('img,.cg-card-artwork')).toHaveCount(0);
  expect((await row.boundingBox())!.height).toBeLessThan(100);
  await expect(row.locator('.cg-type-grid')).toHaveCount(0);
  await page.getByRole('button', { name: 'Pesquisar e filtrar', exact: true }).click();
  await page.getByLabel('Filtrar por responsável').selectOption('one');
  await page.getByRole('button', { name: /Fechar filtros/ }).click();
  await expect(page.getByLabel('Filtrar por responsável')).not.toBeVisible();
  await expect(page.getByText('Atualizando informações…')).not.toBeVisible();
  await page.screenshot({ path: 'output/controle-gasto/mobile-lista-compacta.png', fullPage: true });
  await page.getByRole('tab', { name: 'Instituições', exact: true }).click();
  const bank = page.locator('article.cg-institution').filter({ hasText: data.bank.name });
  const sizes = await bank.locator('footer>button').evaluateAll(buttons => buttons.map(b => ({ w: b.getBoundingClientRect().width, h: b.getBoundingClientRect().height })));
  expect(sizes).toHaveLength(3);
  expect(new Set(sizes.map(s => s.w + ':' + s.h)).size).toBe(1);
  await expect(bank.getByRole('button', { name: 'Ver gastos de ' + data.bank.name })).toHaveText('');
  await page.screenshot({ path: 'output/controle-gasto/mobile-instituicoes-icones.png', fullPage: true });
  await page.getByRole('tab', { name: 'Projeção', exact: true }).click();
  const projection = page.locator('.cg-projection-list>.cg-panel').first();
  await expect(projection).toBeVisible();
  const button = await projection.getByRole('button', { name: 'Ver mês' }).boundingBox();
  const breakdown = await projection.locator('dl').boundingBox();
  expect(button!.y).toBeGreaterThanOrEqual(breakdown!.y + breakdown!.height);
  await page.screenshot({ path: 'output/controle-gasto/mobile-projecao-corrigida.png', fullPage: true });
  await page.getByRole('button', { name: 'Histórico de gastos', exact: true }).click();
  await page.getByLabel('Mês inicial do histórico').fill(data.month);
  await page.getByLabel('Mês final do histórico').fill(data.end);
  await page.getByRole('button', { name: 'OK', exact: true }).click();
  await expect(page.locator('.cg-history-month')).toHaveCount(3);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: 'output/controle-gasto/mobile-historico-gastos.png', fullPage: true });
  await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('tab', { name: 'Gastos', exact: true }).click();
  await expect(page.locator('.cg-bank-list')).toBeVisible();
  await page.getByRole('button', { name: 'Pesquisar e filtrar', exact: true }).click();
  await expect(page.getByLabel('Filtrar por responsável')).toHaveValue('');
  await page.getByRole('button', { name: /Fechar filtros/ }).click();
  await row.locator('button.cg-institution').click();
  await expect(page.locator('.cg-type-grid>.cg-panel').first()).toBeVisible();
  expect((await page.locator('.cg-type-grid>.cg-panel').first().boundingBox())!.height).toBeLessThan(65);
});
