import { expect, test } from '@playwright/test';
import { api, login, uniqueDocument } from './helpers';

test.describe.serial('fluxo operacional principal', () => {
  let clientId = 0;
  let orderId = 0;
  let orderNumber = '';
  const document = uniqueDocument(20260902);

  test.beforeEach(async ({ page }) => login(page));

  test('Master cria Funcionário e o backend bloqueia duplicidade', async ({ page }) => {
    await page.getByRole('button', { name: 'Usuários' }).click();
    await page.getByRole('button', { name: 'Novo usuário' }).click();
    const modal = page.locator('.modal-card');
    const employeePassword = ['Funcionario', String(2026) + String.fromCharCode(33)].join('-');
    await modal.locator('label').filter({ hasText: 'Nome' }).locator('input').fill('Funcionário Homologação');
    await modal.locator('label').filter({ hasText: 'Login' }).locator('input').fill('func.homologacao');
    await modal.locator('select').selectOption({ label: 'Funcionário' });
    await modal.locator('label').filter({ hasText: 'Senha forte' }).locator('input').fill(employeePassword);
    await modal.locator('label').filter({ hasText: 'Confirmar senha' }).locator('input').fill(employeePassword);
    await modal.getByRole('button', { name: 'Salvar' }).click();
    await expect(page.getByText('Funcionário Homologação')).toBeVisible();
  });

  test('cadastra cliente com fallback manual, CPF válido, edição e links', async ({ page }) => {
    await page.getByRole('button', { name: 'Clientes' }).click();
    await page.getByRole('button', { name: 'Novo cliente' }).click();
    const modal = page.getByRole('dialog', { name: 'Novo cliente' });
    await expect(modal).toBeVisible();
    const form = modal.locator('form');
    const values: Record<string, string> = { name: 'Cliente E2E', document, phone: '34999998888', postal_code: '99999999', street: 'Rua Manual', number: '10', district: 'Centro', city: 'Araguari', state: 'MG' };
    for (const [name, value] of Object.entries(values)) await form.locator(`[name="${name}"]`).fill(value);
    await form.getByRole('button', { name: 'Salvar cliente' }).click();
    await expect(page.getByRole('dialog', { name: 'Novo cliente' })).toHaveCount(0);
    const clientCard = page.locator('.client-list article').filter({ hasText: 'Cliente E2E' });
    await expect(clientCard).toBeVisible();
    await expect(clientCard.getByRole('link', { name: 'WhatsApp' })).toHaveAttribute('href', /wa\.me|whatsapp/);
    await expect(clientCard.getByRole('link', { name: 'Maps' })).toHaveAttribute('href', /google/);
    const found = await api(page, `/clients?q=${document}`);
    clientId = found.body.data[0].id;
    await expect(clientCard).toContainText(`Cliente Nº ${clientId}`);
    await expect(clientCard).toContainText('Rua Manual, 10');
    const duplicate = await api(page, '/clients', 'POST', { ...values, name: 'Duplicado', document, postal_code: '99999999' });
    expect(duplicate.status).toBe(422);
  });

  test('abre OS externa com descrição manual, avaria, foto e termo', async ({ page }) => {
    await page.getByRole('button', { name: 'Nova OS', exact: true }).first().click();
    await page.locator('.os-form section').first().locator('select').selectOption(String(clientId));
    const manualEquipment = 'Notebook Dell Inspiron 15 + carregador + mouse';
    await page.getByLabel('Equipamento / Modelo / Acessórios *').fill(manualEquipment);
    await page.getByRole('button', { name: 'ATENDIMENTO EXTERNO' }).click();
    await page.getByLabel('Problema relatado *').fill('Notebook não liga durante homologação');
    const checklist = page.locator('.os-form details').filter({ hasText: 'CHECKLIST DE ENTRADA' });
    await checklist.locator('summary').click();
    await checklist.getByRole('button', { name: 'Notebooks', exact: true }).click();
    await checklist.getByRole('checkbox', { name: 'Carcaça Trincada', exact: true }).check();
    await page.locator('input[type=file]').setInputFiles({ name: 'equipamento.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64') });
    await page.getByRole('button', { name: 'Criar ordem de serviço' }).click();
    await expect(page.getByText('Notebook não liga durante homologação')).toBeVisible();
    await expect(page.getByText(manualEquipment, { exact: true })).toBeVisible();
    const orders = await api(page, '/orders?q=Cliente%20E2E');
    orderId = orders.body.data[0].id;
    orderNumber = orders.body.data[0].number;
    const detail = await api(page, `/orders/${orderId}`);
    expect(detail.body.attendance_type).toBe('external');
    expect(detail.body.equipment_description).toBe(manualEquipment);
    expect(detail.body.photos[0].bytes).toBeLessThanOrEqual(102400);
    expect((await page.request.get(`/api/orders/${orderId}/term`)).status()).toBe(200);
  });

  test('gera e aprova orçamento da OS', async ({ page }) => {
    await page.getByRole('button', { name: 'Ordens de Serviço' }).click();
    const orderRow = page.locator('.order-row').filter({ hasText: 'Cliente E2E' });
    await orderRow.getByRole('button', { name: 'Ver OS' }).click();
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}` })).toBeVisible();
    await expect(page.getByText('Pagamento ainda não registrado.', { exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Registrar pagamento' })).toHaveCount(0);
    await expect(page.getByText(/NaN|Invalid Date/)).toHaveCount(0);
    await page.getByRole('button', { name: 'Gerar orçamento' }).click();
    const budgetForm = page.getByRole('dialog', { name: 'Gerar orçamento' });
    await expect(budgetForm).toBeVisible();
    await budgetForm.getByLabel('Diagnóstico').fill('Falha de energia');
    await budgetForm.getByLabel('Serviço proposto').fill('Reparo completo');
    await budgetForm.getByLabel('Validade (dias)').fill('7');
    await budgetForm.getByLabel('Buscar serviço ou produto para o orçamento').fill('Formatação');
    const catalogResult = budgetForm.getByRole('button', { name: 'Adicionar Formatação E2E' });
    await expect(catalogResult).toBeVisible();
    await catalogResult.click();
    const selectedItem = budgetForm.locator('.finish-item').filter({ hasText: 'Formatação' });
    await expect(selectedItem).toBeVisible();
    await selectedItem.getByLabel(/Quantidade de/).fill('1');
    await selectedItem.getByLabel(/Valor unitário de/).fill('150,00');
    await budgetForm.getByRole('button', { name: 'Salvar e gerar PDF' }).click();
    const budgetsSection = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Orçamentos', exact: true }) });
    await expect(budgetsSection.getByText(/Revisão 1/)).toBeVisible();
    await expect(budgetsSection.getByRole('link', { name: 'Abrir PDF' })).toHaveAttribute('href', `/api/orders/${orderId}/budgets/1/pdf`);
    await budgetsSection.getByRole('button', { name: 'Marcar enviado' }).click();
    await expect(budgetsSection.getByRole('button', { name: 'Aprovar orçamento' })).toBeVisible();
    const approvalRequestPromise = page.waitForRequest((request) => request.url().endsWith(`/api/orders/${orderId}/budgets/1/status`) && request.method() === 'PATCH');
    await budgetsSection.getByRole('button', { name: 'Aprovar orçamento' }).click();
    const approvalPayload = (await approvalRequestPromise).postDataJSON();
    expect(approvalPayload).toEqual({ status: 'approved' });
    expect(approvalPayload).not.toHaveProperty('copy_items');
    await expect(budgetsSection.getByRole('button', { name: 'Aprovar orçamento' })).toHaveCount(0);

    const services = await api(page, '/catalogs/services');
    const formatting = services.body.find((row: any) => row.name === 'Formatação E2E');
    const secondBudget = await api(page, `/orders/${orderId}/budgets`, 'POST', {
      diagnosis: 'Revisão descartável', proposal: 'Teste de exclusão lógica', validity_days: 7,
      items: [{ catalog_id: formatting.id, description: formatting.name, quantity: 1, unit_price_cents: formatting.price_cents, warranty_enabled: false }],
    });
    expect(secondBudget.status).toBe(201);
    await page.reload();
    await expect(budgetsSection.getByText(/Revisão 2/)).toBeVisible();
    page.once('dialog', async (dialog) => {
      expect(dialog.type()).toBe('confirm');
      expect(dialog.message()).toContain('Revisão 2');
      await dialog.accept();
    });
    await budgetsSection.getByText(/Revisão 2/).getByRole('button', { name: 'Excluir orçamento' }).click();
    await expect(budgetsSection.getByText(/Revisão 2/)).toHaveCount(0);
    const remainingBudgets = await api(page, `/orders/${orderId}/budgets`);
    expect(remainingBudgets.body).toHaveLength(1);
  });

  test('finaliza OS usando o orçamento aprovado', async ({ page }) => {
    await page.getByRole('button', { name: 'Ordens de Serviço' }).click();
    const orderRow = page.locator('.order-row').filter({ hasText: 'Cliente E2E' });
    await orderRow.getByRole('button', { name: 'Ver OS' }).click();
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}` })).toBeVisible();
    const statusSelect = page.locator('.status-picker select');
    const statusHistory = page.locator('details.arl-record-accordion').filter({ hasText: 'Histórico de status' });
    await statusHistory.locator('summary').click();
    await expect(statusSelect.locator('option[value="in_service"]'), 'Fluxo operacional deve manter Em Serviço como opção válida').toHaveText('Em Serviço');
    await statusSelect.selectOption('in_service');
    await expect(statusHistory.getByText(/Em Serviço ·/)).toBeVisible();
    await statusSelect.selectOption('waiting_part');
    await expect(statusHistory.getByText(/Aguardando ·/)).toBeVisible();
    await statusSelect.selectOption('analysis');
    await expect(statusHistory.getByText(/Em Análise ·/)).toBeVisible();
    await statusSelect.selectOption('completed');
    const finalModal = page.locator('.modal-card').filter({ hasText: 'FINALIZAÇÃO DA OS' });
    await expect(finalModal).toBeVisible();
    await finalModal.getByRole('button', { name: 'USAR ITENS DO ORÇAMENTO APROVADO' }).click();
    await expect(finalModal.getByText(/Itens vinculados ao orçamento aprovado/)).toBeVisible();
    await finalModal.locator('textarea').fill('Equipamento testado e funcionando.');
    const finalizeRequestPromise = page.waitForRequest((request) => request.url().endsWith(`/api/orders/${orderId}/finalize`) && request.method() === 'POST');
    const finalShareResponsePromise = page.waitForResponse((response) => response.url().endsWith(`/api/orders/${orderId}/final-share`) && response.request().method() === 'GET');
    await finalModal.getByRole('button', { name: 'Salvar e concluir OS' }).click();
    const finalizePayload = (await finalizeRequestPromise).postDataJSON();
    expect(finalizePayload.approved_budget_id).toBeTruthy();
    expect(finalizePayload).not.toHaveProperty('items');
    await expect(statusSelect).toHaveValue('completed');
    await expect(page.locator('.completion').getByText('Finalizado', { exact: true })).toBeVisible();
    const documents = page.locator('details.arl-record-accordion').filter({ hasText: 'Documentos' });
    await documents.locator('summary').click();
    await expect(documents.getByText('PDF Final', { exact: true })).toBeVisible();
    const finalizedResponse = await page.request.get(`/api/orders/${orderId}`);
    expect(finalizedResponse.status()).toBe(200);
    const finalized = await finalizedResponse.json();
    expect(finalized.items[0].source_budget_id).toBeTruthy();
    expect(finalized.items[0].description).toBe('Formatação E2E');
    await expect(page.getByRole('button', { name: 'Gerar orçamento' })).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Excluir orçamento' })).toHaveCount(0);
    const blockedDeletion = await api(page, `/orders/${orderId}/budgets/1`, 'DELETE');
    expect(blockedDeletion.status).toBe(409);
    expect(blockedDeletion.body?.message).toBe('Não é possível excluir orçamento de uma OS finalizada.');
    const blockedBudget = await api(page, `/orders/${orderId}/budgets`, 'POST', {});
    expect(blockedBudget.status).toBe(409);
    expect(blockedBudget.body?.message).toBe('Não é possível criar orçamento para uma OS finalizada.');
    const finalShareResponse = await finalShareResponsePromise;
    expect(finalShareResponse.status()).toBe(200);
    const finalShare = await finalShareResponse.json();
    expect(finalShare.url).toContain(`/share/orders/${orderId}/final/1`);
    const whatsappHref = await page.getByRole('link', { name: 'Enviar PDF pelo WhatsApp' }).getAttribute('href');
    expect(whatsappHref).toMatch(/wa\.me/);
    expect(decodeURIComponent(whatsappHref || '')).not.toContain('Acesse o PDF da Ordem de Serviço aqui');
    await page.reload();
    const documentMenu = page.locator('.arl-opening-call');
    await documentMenu.locator('summary').click();
    await expect(documentMenu.getByRole('button', { name: 'Relatório Técnico Final' })).toBeVisible();
    await expect(documentMenu.getByRole('button', { name: 'Reabrir OS' })).toBeVisible();
  });

  test('registra pagamento parcial e valida A Receber', async ({ page }) => {
    await page.getByRole('button', { name: 'Ordens de Serviço' }).click();
    const orderRow = page.locator('.order-row').filter({ hasText: 'Cliente E2E' });
    await orderRow.getByRole('button', { name: 'Ver OS' }).click();
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}` })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Registrar pagamento' })).toBeVisible();
    await page.getByRole('button', { name: 'Registrar pagamento' }).click();
    const paymentModal = page.locator('.modal-card').filter({ hasText: `Pagamento da OS #${orderNumber}` });
    await expect(paymentModal.getByRole('button', { name: /Pagar valor total/ })).toBeVisible();
    await paymentModal.getByLabel('Valor recebido (R$)').fill('50,00');
    await paymentModal.getByLabel('Forma de pagamento *').selectOption('pix');
    await expect(paymentModal.getByText(/R\$ 100,00.*A Receber/)).toBeVisible();
    await paymentModal.getByRole('button', { name: 'Confirmar pagamento' }).click();
    await expect(page.getByText(/Pagamento parcial/)).toBeVisible();
    await expect(page.getByText(/ainda faltam R\$ 100,00/)).toBeVisible();
    const partialResponse = await page.request.get(`/api/orders/${orderId}/payments`);
    expect(partialResponse.status()).toBe(200);
    const partial = await partialResponse.json();
    expect(partial.paid_cents).toBe(5000);
    expect(partial.balance_cents).toBe(10000);
    expect(partial.status).toBe('partial');
    await page.getByRole('button', { name: 'Financeiro' }).click();
    await expect(page.getByRole('heading', { name: 'Financeiro' })).toBeVisible();
    const receivablesResponsePromise = page.waitForResponse((response) => response.url().endsWith('/api/finance/receivables') && response.request().method() === 'GET');
    await page.getByRole('button', { name: 'A Receber' }).click();
    await expect(page.getByText(`OS #${orderNumber} · Cliente E2E`)).toBeVisible();
    await expect(page.getByText('Falta R$ 100,00')).toBeVisible();
    const receivablesResponse = await receivablesResponsePromise;
    expect(receivablesResponse.status()).toBe(200);
    const receivables = await receivablesResponse.json();
    expect(receivables.data.find((row: { id: number }) => row.id === orderId)?.balance_cents).toBe(10000);
  });

  test('quita saldo restante pela UI', async ({ page }) => {
    await page.getByRole('button', { name: 'Financeiro' }).click();
    await expect(page.getByRole('heading', { name: 'Financeiro' })).toBeVisible();
    await page.getByRole('button', { name: 'A Receber' }).click();
    const receivableRow = page.locator('.transaction').filter({ hasText: `OS #${orderNumber}` });
    await expect(receivableRow).toBeVisible();
    await receivableRow.getByRole('button', { name: 'Abrir OS' }).click();
    await page.getByRole('button', { name: 'Registrar novo pagamento' }).click();
    const finalPaymentModal = page.locator('.modal-card').filter({ hasText: `Pagamento da OS #${orderNumber}` });
    await finalPaymentModal.getByRole('button', { name: /Pagar valor total/ }).click();
    await finalPaymentModal.getByRole('button', { name: 'Confirmar pagamento' }).click();
    await expect(page.getByText('Pago integralmente')).toBeVisible();
    await expect(page.getByText('Saldo zerado.')).toBeVisible();
    const paidResponse = await page.request.get(`/api/orders/${orderId}/payments`);
    expect(paidResponse.status()).toBe(200);
    const paid = await paidResponse.json();
    expect(paid.paid_cents).toBe(15000);
    expect(paid.balance_cents).toBe(0);
    expect(paid.status).toBe('paid');
  });

  test('reabre a mesma OS, finaliza nova revisão e ajusta cobrança', async ({ page }) => {
    await page.goto(`/orders/${orderId}`);
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}` })).toBeVisible();
    const menu = page.locator('.arl-opening-call');
    await menu.locator('summary').click();
    await menu.getByRole('button', { name: 'Reabrir OS' }).click();
    const reopen = page.getByRole('dialog', { name: `Reabrir OS #${orderNumber}` });
    await reopen.locator('textarea').fill('Correção do valor cobrado após conferência.');
    await reopen.getByRole('button', { name: 'Confirmar reabertura' }).click();
    await expect(page.locator('.status-picker select')).toHaveValue('analysis');
    await page.getByRole('button', { name: 'Concluir OS' }).click();
    const finalModal = page.getByRole('dialog', { name: 'FINALIZAÇÃO DA OS' });
    await finalModal.getByLabel('Valor unitário de Formatação E2E').fill('140,00');
    await finalModal.locator('textarea').fill('Valor corrigido e equipamento reconferido.');
    await finalModal.getByRole('button', { name: 'Salvar e concluir OS' }).click();
    await expect(page.locator('.status-picker select')).toHaveValue('completed');
    const documents = page.locator('details.arl-record-accordion').filter({ hasText: 'Documentos' });
    await documents.locator('summary').click();
    await expect(documents.getByText('Revisão 2', { exact: false })).toBeVisible();
    const audit = page.locator('details.arl-record-accordion').filter({ hasText: 'Histórico de alterações' });
    await audit.locator('summary').click();
    await expect(audit.getByText('Reabertura da OS', { exact: true })).toBeVisible();
    const payments = await api(page, `/orders/${orderId}/payments`);
    expect(payments.body.paid_cents).toBe(14000);
    const daily = await api(page, '/finance/daily');
    expect(daily.body.transactions.filter((row: any) => row.order_number === orderNumber).reduce((sum: number, row: any) => sum + row.effective_cents, 0)).toBe(14000);
  });

  test('histórico do cliente e pós-venda aparecem imediatamente, mas ficam bloqueados por 24h', async ({ page }) => {
    await page.getByRole('button', { name: 'Clientes' }).click();
    const clientCard = page.locator('.client-list article').filter({ hasText: 'Cliente E2E' });
    await clientCard.getByRole('button', { name: 'Visualizar' }).click();
    await expect(page.getByRole('heading', { name: 'Cliente E2E' })).toBeVisible();
    await expect(page.getByText(`OS #${orderNumber}`)).toBeVisible();
    await expect(page.getByText('Formatação E2E', { exact: true })).toBeVisible();
    await expect(page.getByRole('link', { name: '2ª via PDF A4' })).toHaveAttribute('href', `/api/orders/${orderId}/final/1/pdf`);
    const history = await api(page, `/clients/${clientId}`);
    expect(history.body.orders.some((order: { id: number }) => order.id === orderId)).toBeTruthy();
    const historicalOrder = history.body.orders.find((order: { id: number }) => order.id === orderId);
    expect(historicalOrder.items.some((item: { description: string }) => item.description === 'Formatação E2E')).toBeTruthy();
    await page.getByRole('button', { name: 'Pós-Venda' }).click();
    await expect(page.getByRole('heading', { name: 'Pós-Venda' })).toBeVisible();
    const lockedRow = page.locator('.post-sale article').filter({ hasText: `OS ${orderNumber}` });
    await expect(lockedRow).toBeVisible();
    const lockedActions = lockedRow.locator('.post-action');
    await expect(lockedActions).toHaveCount(2);
    for (let i = 0; i < 2; i += 1) {
      await expect(lockedActions.nth(i)).not.toHaveAttribute('href');
      await expect(lockedActions.nth(i)).toHaveCSS('pointer-events', 'none');
    }
    const lockLabel = await lockedRow.locator('div').first().evaluate((element) => getComputedStyle(element, '::after').content);
    expect(lockLabel).toContain('Disponível após 24 horas');
    const postSale = await api(page, '/post-sales');
    expect(postSale.status).toBe(200);
    const cycle = postSale.body.find((row: { number: string }) => row.number === orderNumber);
    expect(cycle).toBeTruthy();
    expect(cycle.available).toBe(false);
    expect(cycle.eligible_at).toBeTruthy();
    expect(cycle.whatsapp.google).toBeNull();
    const blocked = await api(page, `/post-sales/${cycle.id}/google/confirm`, 'POST', {});
    expect(blocked.status).toBe(409);
  });
});
