import { selectNewOrderClient } from './helpers';
import { expect, test } from '@playwright/test';
import { api, login, uniqueDocument } from './helpers';

test.describe.serial('fluxo operacional principal', () => {
  let clientId = 0;
  let orderId = 0;
  let orderNumber = '';
  const document = uniqueDocument(20260902);

  test.beforeEach(async ({ page }) => login(page));

  test('Master cria Funcionário e o backend bloqueia duplicidade', async ({ page }) => {
    await page.getByRole('button', { name: 'Usuários' }).click();
    await page.getByRole('button', { name: 'Novo usuário' }).click();
    const modal = page.locator('.modal-card');
    const employeePassword = ['Funcionario', String(2026) + String.fromCharCode(33)].join('-');
    await modal.locator('label').filter({ hasText: 'Nome' }).locator('input').fill('Funcionário Homologação');
    await modal.locator('label').filter({ hasText: 'Login' }).locator('input').fill('func.homologacao');
    await modal.locator('select').selectOption({ label: 'Funcionário' });
    await modal.locator('label').filter({ hasText: 'Senha forte' }).locator('input').fill('fraca');
    await modal.locator('label').filter({ hasText: 'Confirmar senha' }).locator('input').fill('fraca');
    await modal.getByRole('button', { name: 'Salvar' }).click();
    await expect(modal.getByRole('alert')).toContainText('A senha precisa conter pelo menos 12 caracteres, uma letra maiúscula, um número, um caractere especial.');
    await modal.locator('label').filter({ hasText: 'Senha forte' }).locator('input').fill(employeePassword);
    await modal.locator('label').filter({ hasText: 'Confirmar senha' }).locator('input').fill(employeePassword);
    await modal.getByRole('button', { name: 'Salvar' }).click();
    await expect(page.getByText('Funcionário Homologação')).toBeVisible();
  });

  test('cadastra cliente com fallback manual, CPF válido, edição e links', async ({ page }) => {
    await page.route('https://viacep.com.br/**', route => route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ erro: true }),
    }));
    await page.getByRole('button', { name: 'Clientes' }).click();
    await page.getByRole('button', { name: 'Novo cliente' }).click();
    const modal = page.getByTestId('client-modal');
    await expect(modal).toBeVisible();
    const form = modal.getByTestId('client-form');
    const values: Record<string, string> = { name: 'Cliente E2E', document, phone: '34999998888', postal_code: '99999999', street: 'Rua Manual', number: '10', district: 'Centro', city: 'Araguari', state: 'MG' };
    for (const [name, value] of Object.entries(values)) await form.locator(`[name="${name}"]`).fill(value);
    await expect(form.getByText('ViaCEP indisponível. Preencha o endereço manualmente.', { exact: true })).toBeVisible();
    await form.getByRole('button', { name: 'Salvar cliente' }).click();
    await expect(page.getByTestId('client-modal')).toHaveCount(0);
    await page.getByPlaceholder(/Nome, telefone/).fill('Cliente E2E');
    const clientCard = page.locator('.client-list article').filter({ hasText: 'Cliente E2E' });
    await expect(clientCard).toBeVisible();
    await expect(clientCard.getByRole('link', { name: 'WhatsApp' })).toHaveAttribute('href', /wa\.me|whatsapp/);
    await expect(clientCard.getByRole('link', { name: 'Maps' })).toHaveAttribute('href', /google/);
    const found = await api(page, `/clients?q=${document}`);
    clientId = found.body.data[0].id;
    await expect(clientCard).toContainText(`Cliente Nº ${clientId}`);
    await expect(clientCard).toContainText('Rua Manual, 10');
    const duplicate = await api(page, '/clients', 'POST', { ...values, name: 'Duplicado', document, postal_code: '99999999' });
    expect(duplicate.status).toBe(422);
  });

  test('abre OS externa com descrição manual, estado físico preenchido, foto e termo', async ({ page }) => {
    await page.getByRole('button', { name: 'Nova OS', exact: true }).first().click();
    await selectNewOrderClient(page, clientId);
    const manualEquipment = 'Notebook Dell Inspiron 15 + carregador + mouse';
    await page.getByLabel('Equipamento *').fill(manualEquipment);
    await page.getByRole('button', { name: 'ATENDIMENTO EXTERNO' }).click();
    const reportedProblem = page.getByLabel('Problema relatado *');
    await expect(reportedProblem).toHaveAttribute('spellcheck', 'true');
    await reportedProblem.fill('Notebook não liga durante homologação');
    const intakeCondition = 'Carcaça trincada no canto esquerdo e marcas de queda';
    const intakeField = page.getByLabel('Estado físico do equipamento na entrada');
    await expect(intakeField).toHaveAttribute('spellcheck', 'true');
    await intakeField.fill(intakeCondition);
    await page.locator('input[type=file]').setInputFiles({ name: 'equipamento.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64') });
    await page.getByRole('button', { name: 'Criar ordem de serviço' }).click();
    await expect(page.getByText('Notebook não liga durante homologação')).toBeVisible();
    await expect(page.locator('.arl-intake-equipment-field').getByText(manualEquipment, { exact: true })).toBeVisible();
    const orders = await api(page, '/orders?q=Cliente%20E2E');
    orderId = orders.body.data[0].id;
    orderNumber = orders.body.data[0].number;
    const detail = await api(page, `/orders/${orderId}`);
    expect(detail.body.attendance_type).toBe('external');
    expect(detail.body.equipment_description).toBe(manualEquipment);
    expect(detail.body.intake_condition).toBe(intakeCondition);
    expect(detail.body.photos[0].bytes).toBeLessThanOrEqual(102400);
    expect((await page.request.get(`/api/orders/${orderId}/term`)).status()).toBe(200);
  });

  test('gera e aprova orçamento da OS', async ({ page }) => {
    await page.getByRole('button', { name: 'Ordens' }).click();
    await page.getByRole('tablist', { name: 'Filtrar ordens' }).getByRole('button', { name: 'Todas', exact: true }).click();
    const orderRow = page.locator('.order-row').filter({ hasText: 'Cliente E2E' });
    await orderRow.getByRole('button', { name: 'Ver OS' }).click();
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}`, exact: true })).toBeVisible();
    await expect(page.getByText('Pagamento ainda não registrado.', { exact: true })).toBeVisible();
    await expect(page.locator('[data-order-action="payment"]')).toHaveCount(0);
    await expect(page.getByText(/NaN|Invalid Date/)).toHaveCount(0);
    await page.locator('[data-order-action="budget"]').click();
    const budgetForm = page.getByRole('dialog', { name: 'Gerar orçamento' });
    await expect(budgetForm).toBeVisible();
    await budgetForm.getByLabel('Diagnóstico').fill('Falha de energia');
    await budgetForm.getByLabel('Serviço proposto').fill('Reparo completo');
    await budgetForm.getByLabel('Validade (dias)').fill('7');
    await budgetForm.getByRole('button', { name: 'Adicionar serviços' }).click();
    const catalogPicker = page.getByRole('dialog', { name: 'Selecionar Produto ou Serviço' });
    await expect(catalogPicker).toBeVisible();
    await catalogPicker.getByRole('button', { name: 'Fechar seletor' }).click();
    await budgetForm.getByLabel('Buscar serviço ou produto para o orçamento').fill('Formatação');
    const catalogResult = budgetForm.getByRole('button', { name: 'Adicionar Formatação E2E' });
    await expect(catalogResult).toBeVisible();
    await expect(catalogResult).toHaveCSS('text-align', 'left');
    expect(parseFloat(await catalogResult.evaluate((element) => getComputedStyle(element).borderRadius))).toBeGreaterThan(0);
    await catalogResult.click();
    const selectedItem = budgetForm.locator('.finish-item').filter({ hasText: 'Formatação' });
    await expect(selectedItem).toBeVisible();
    await selectedItem.getByLabel(/Quantidade de/).fill('1');
    await selectedItem.getByLabel(/Valor unitário de/).fill('150,00');
    await budgetForm.getByRole('button', { name: 'Salvar e gerar PDF' }).click();
    const budgetsSection = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Orçamentos', exact: true }) });
    await expect(budgetsSection.getByText(/Revisão 1/)).toBeVisible();
    await expect(budgetsSection.getByText(/Revisão 1 · Rascunho · R\$ 150,00/)).toBeVisible();
    await expect(budgetsSection.getByRole('link', { name: 'Abrir PDF' })).toHaveAttribute('href', `/api/orders/${orderId}/budgets/1/pdf`);
    await budgetsSection.getByRole('button', { name: 'Marcar enviado' }).click();
    await expect(budgetsSection.getByText(/Revisão 1 · Enviado · R\$ 150,00/)).toBeVisible();
    await expect(budgetsSection.getByRole('button', { name: 'Aprovar orçamento' })).toBeVisible();
    const approvalRequestPromise = page.waitForRequest((request) => request.url().endsWith(`/api/orders/${orderId}/budgets/1/status`) && request.method() === 'PATCH');
    await budgetsSection.getByRole('button', { name: 'Aprovar orçamento' }).click();
    const approvalPayload = (await approvalRequestPromise).postDataJSON();
    expect(approvalPayload).toEqual({ status: 'approved' });
    expect(approvalPayload).not.toHaveProperty('copy_items');
    await expect(budgetsSection.getByRole('button', { name: 'Aprovar orçamento' })).toHaveCount(0);
    await expect(budgetsSection.getByText(/Revisão 1 · Aprovado · R\$ 150,00/)).toBeVisible();

    const services = await api(page, '/catalogs/services');
    const formatting = services.body.find((row: any) => row.name === 'Formatação E2E');
    const secondBudget = await api(page, `/orders/${orderId}/budgets`, 'POST', {
      diagnosis: 'Revisão descartável', proposal: 'Teste de exclusão lógica', validity_days: 7,
      items: [{ catalog_id: formatting.id, description: formatting.name, quantity: 1, unit_price_cents: formatting.price_cents, warranty_enabled: false }],
    });
    expect(secondBudget.status).toBe(201);
    await page.reload();
    await expect(budgetsSection.getByText(/Revisão 2/)).toBeVisible();
    page.once('dialog', async (dialog) => {
      expect(dialog.type()).toBe('confirm');
      expect(dialog.message()).toContain('Revisão 2');
      await dialog.accept();
    });
    await budgetsSection.getByText(/Revisão 2/).getByRole('button', { name: 'Excluir orçamento' }).click();
    await expect(budgetsSection.getByText(/Revisão 2/)).toHaveCount(0);
    const remainingBudgets = await api(page, `/orders/${orderId}/budgets`);
    expect(remainingBudgets.body).toHaveLength(1);
  });

  test('finaliza OS usando o orçamento aprovado', async ({ page }) => {
    await page.getByRole('button', { name: 'Ordens' }).click();
    await page.getByRole('tablist', { name: 'Filtrar ordens' }).getByRole('button', { name: 'Todas', exact: true }).click();
    const orderRow = page.locator('.order-row').filter({ hasText: 'Cliente E2E' });
    await orderRow.getByRole('button', { name: 'Ver OS' }).click();
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}`, exact: true })).toBeVisible();
    await expect(page.locator('.status-picker')).toHaveCount(0);
    for (const nextStatus of ['in_service', 'waiting_part', 'analysis']) {
      const changed = await api(page, `/orders/${orderId}/status`, 'PATCH', { status: nextStatus });
      expect(changed.status).toBe(200);
    }
    const statusHistory = await api(page, `/orders/${orderId}`);
    expect(statusHistory.body.histories.map((entry: any) => entry.to_status)).toEqual(expect.arrayContaining(['in_service', 'waiting_part', 'analysis']));
    await page.getByRole('button', { name: 'Concluir', exact: true }).click();
    const finalModal = page.locator('.modal-card').filter({ hasText: 'FINALIZAÇÃO DA OS' });
    await expect(finalModal).toBeVisible();
    await finalModal.getByRole('button', { name: 'USAR ITENS DO ORÇAMENTO APROVADO' }).click();
    await expect(finalModal.getByText(/Itens vinculados ao orçamento aprovado/)).toBeVisible();
    await finalModal.locator('textarea').fill('Equipamento testado e funcionando.');
    const finalizeRequestPromise = page.waitForRequest((request) => request.url().endsWith(`/api/orders/${orderId}/finalize`) && request.method() === 'POST');
    await finalModal.getByRole('button', { name: 'Salvar e concluir OS' }).click();
    const finalizePayload = (await finalizeRequestPromise).postDataJSON();
    expect(finalizePayload.approved_budget_id).toBeTruthy();
    expect(finalizePayload).not.toHaveProperty('items');
    const completion = page.getByRole('status', { name: 'Compartilhar fechamento da OS' });
    await expect(completion).toBeVisible();
    await expect(completion.getByText(`OS #${orderNumber} finalizada`, { exact: true })).toBeVisible();
    const documents = await api(page, `/orders/${orderId}/documents`);
    expect(documents.body.some((document: any) => document.type === 'final')).toBe(true);
    const finalizedResponse = await page.request.get(`/api/orders/${orderId}`);
    expect(finalizedResponse.status()).toBe(200);
    const finalized = await finalizedResponse.json();
    expect(finalized.items[0].source_budget_id).toBeTruthy();
    expect(finalized.items[0].description).toBe('Formatação E2E');
    await expect(page.locator('[data-order-action="budget"]')).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Excluir orçamento' })).toHaveCount(0);
    const blockedDeletion = await api(page, `/orders/${orderId}/budgets/1`, 'DELETE');
    expect(blockedDeletion.status).toBe(409);
    expect(blockedDeletion.body?.message).toBe('Não é possível excluir orçamento de uma OS fechada.');
    const blockedBudget = await api(page, `/orders/${orderId}/budgets`, 'POST', {});
    expect(blockedBudget.status).toBe(409);
    expect(blockedBudget.body?.message).toBe('Não é possível criar orçamento para uma OS fechada.');
    const finalShareResponsePromise = page.waitForResponse((response) => response.url().endsWith(`/api/orders/${orderId}/final-share`) && response.request().method() === 'GET');
    const popupPromise = page.context().waitForEvent('page');
    await page.getByRole('status', { name: 'Compartilhar fechamento da OS' }).getByRole('button', { name: 'Enviar PDF pelo WhatsApp' }).click();
    const whatsappPage = await popupPromise;
    await expect.poll(() => whatsappPage.url()).toMatch(/api\.whatsapp\.com\/send/);
    const finalShareResponse = await finalShareResponsePromise;
    expect(finalShareResponse.status()).toBe(200);
    const finalShare = await finalShareResponse.json();
    expect(finalShare.url).toContain(`/share/orders/${orderId}/final/1`);
    const whatsappHref = whatsappPage.url();
    const whatsappText = decodeURIComponent(new URL(whatsappHref).searchParams.get('text') || '');
    expect(whatsappText).toContain(finalShare.url);
    expect(whatsappText).toContain('Detalhes do Serviço no link abaixo');
    await whatsappPage.close();
    await page.reload();
    const documentMenu = page.locator('.arl-opening-call');
    await documentMenu.getByRole('button', { name: "PDF's", exact: true }).click();
    const finalReportButton = documentMenu.getByRole('button', { name: 'Relatório Técnico Final' });
    await expect(finalReportButton).toBeVisible();
    const finalPdfPromise = page.context().waitForEvent('page');
    await finalReportButton.click();
    const finalPdf = await finalPdfPromise;
    await expect.poll(() => new URL(finalPdf.url()).pathname).toBe(`/api/orders/${orderId}/final/1/pdf`);
    await finalPdf.close();
    await expect(documentMenu.getByRole('button', { name: 'Reabrir OS' })).toBeVisible();
  });

  test('registra pagamento parcial e valida A Receber', async ({ page }) => {
    await page.getByRole('button', { name: 'Ordens' }).click();
    await page.getByRole('tablist', { name: 'Filtrar ordens' }).getByRole('button', { name: 'Todas', exact: true }).click();
    const orderRow = page.locator('.order-row').filter({ hasText: 'Cliente E2E' });
    await orderRow.getByRole('button', { name: 'Ver OS' }).click();
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}`, exact: true })).toBeVisible();
    await expect(page.locator('[data-order-action="payment"]')).toBeVisible();
    await page.locator('[data-order-action="payment"]').click();
    const paymentModal = page.locator('.modal-card').filter({ hasText: `Pagamento da OS #${orderNumber}` });
    await expect(paymentModal.getByRole('button', { name: /Pagar valor total/ })).toBeVisible();
    await paymentModal.getByLabel('Valor recebido (R$)').fill('50,00');
    await paymentModal.getByLabel('Forma de pagamento *').selectOption('pix');
    await expect(paymentModal.getByText(/R\$ 100,00.*A Receber/)).toBeVisible();
    await paymentModal.getByRole('button', { name: 'Confirmar pagamento' }).click();
    await expect(page.getByText(/Pagamento parcial/)).toBeVisible();
    await expect(page.getByText(/ainda faltam R\$ 100,00/)).toBeVisible();
    const partialResponse = await page.request.get(`/api/orders/${orderId}/payments`);
    expect(partialResponse.status()).toBe(200);
    const partial = await partialResponse.json();
    expect(partial.paid_cents).toBe(5000);
    expect(partial.balance_cents).toBe(10000);
    expect(partial.status).toBe('partial');
    await page.getByRole('button', { name: 'Financeiro' }).click();
    await expect(page.getByRole('heading', { name: 'Financeiro' })).toBeVisible();
    const receivablesResponsePromise = page.waitForResponse((response) => response.url().endsWith('/api/finance/receivables') && response.request().method() === 'GET');
    await page.getByRole('button', { name: 'A Receber' }).click();
    await expect(page.getByText(`OS #${orderNumber} · Cliente E2E`)).toBeVisible();
    await expect(page.getByText('Falta R$ 100,00')).toBeVisible();
    const receivablesResponse = await receivablesResponsePromise;
    expect(receivablesResponse.status()).toBe(200);
    const receivables = await receivablesResponse.json();
    expect(receivables.data.find((row: { id: number }) => row.id === orderId)?.balance_cents).toBe(10000);
  });

  test('quita saldo restante pela UI', async ({ page }) => {
    await page.getByRole('button', { name: 'Financeiro' }).click();
    await expect(page.getByRole('heading', { name: 'Financeiro' })).toBeVisible();
    await page.getByRole('button', { name: 'A Receber' }).click();
    const receivableRow = page.locator('.transaction').filter({ hasText: `OS #${orderNumber}` });
    await expect(receivableRow).toBeVisible();
    await receivableRow.getByRole('button', { name: 'Abrir OS' }).click();
    await page.locator('[data-order-action="payment"]').click();
    const finalPaymentModal = page.locator('.modal-card').filter({ hasText: `Pagamento da OS #${orderNumber}` });
    await finalPaymentModal.getByRole('button', { name: /Pagar valor total/ }).click();
    await finalPaymentModal.getByRole('button', { name: 'Confirmar pagamento' }).click();
    await expect(page.getByText('Pago integralmente')).toBeVisible();
    await expect(page.getByText('Saldo zerado.')).toBeVisible();
    const paidResponse = await page.request.get(`/api/orders/${orderId}/payments`);
    expect(paidResponse.status()).toBe(200);
    const paid = await paidResponse.json();
    expect(paid.paid_cents).toBe(15000);
    expect(paid.balance_cents).toBe(0);
    expect(paid.status).toBe('paid');
  });

  test('reabre a mesma OS e preserva o recebimento antigo ao reduzir o total', async ({ page }) => {
    await page.goto(`/orders/${orderId}`);
    await expect(page.getByRole('heading', { name: `OS #${orderNumber}`, exact: true })).toBeVisible();
    const menu = page.locator('.arl-opening-call');
    await menu.getByRole('button', { name: "PDF's", exact: true }).click();
    await menu.getByRole('button', { name: 'Reabrir OS' }).click();
    const reopen = page.getByRole('dialog', { name: `Reabrir OS #${orderNumber}` });
    await reopen.locator('textarea').fill('Correção do valor cobrado após conferência.');
    await reopen.getByRole('button', { name: 'Confirmar reabertura' }).click();
    await expect(page.locator('.status-picker')).toHaveCount(0);
    await expect(page.getByText('Reaberta', { exact: true })).toBeVisible();
    const reopenedOrder = await api(page, `/orders/${orderId}`);
    expect(reopenedOrder.body.status).toBe('analysis');
    await page.getByRole('button', { name: 'Concluir', exact: true }).click();
    const finalModal = page.getByRole('dialog', { name: 'FINALIZAÇÃO DA OS' });
    await finalModal.getByLabel('Valor unitário de Formatação E2E').fill('140,00');
    await finalModal.locator('textarea').fill('Valor corrigido e equipamento reconferido.');
    const refinalizationResponsePromise = page.waitForResponse((response) => response.url().endsWith(`/api/orders/${orderId}/finalize`) && response.request().method() === 'POST');
    await finalModal.getByRole('button', { name: 'Salvar e concluir OS' }).click();
    expect((await refinalizationResponsePromise).status()).toBe(201);
    const refinalizedOrder = await api(page, `/orders/${orderId}`);
    expect(refinalizedOrder.body.status).toBe('completed');
    expect(refinalizedOrder.body.display_status).toBe('paid');
    const documents = await api(page, `/orders/${orderId}/documents`);
    expect(documents.body.some((document: any) => document.type === 'final' && document.revision === 2)).toBe(true);
    expect(documents.body.filter((document: any) => document.type === 'budget' && document.revision === 2), 'A outra Revisão 2 é o orçamento histórico, não uma duplicata do fechamento').toHaveLength(1);
    const audit = await api(page, `/orders/${orderId}/audit-history`);
    const reopenAudit = audit.body.find((entry: any) => entry.action === 'Reabertura da OS');
    expect(reopenAudit).toBeTruthy();
    expect(reopenAudit.changes).toContain('Motivo: Correção do valor cobrado após conferência.');
    const auditChanges = audit.body.flatMap((entry: any) => entry.changes);
    expect(auditChanges).toContain('Valor alterado de R$ 150,00 para R$ 140,00');
    expect(auditChanges).not.toContain('Ajuste de cobrança registrado no financeiro para esta OS.');
    const payments = await api(page, `/orders/${orderId}/payments`);
    expect(payments.body.paid_cents).toBe(15000);
    expect(payments.body.balance_cents).toBe(0);
    const daily = await api(page, '/finance/daily');
    expect(daily.body.transactions.filter((row: any) => row.order_number === orderNumber).reduce((sum: number, row: any) => sum + row.effective_cents, 0)).toBe(15000);
  });

  test('histórico do cliente e pós-venda aparecem imediatamente, mas ficam bloqueados por 7 dias', async ({ page }) => {
    await page.getByRole('button', { name: 'Clientes' }).click();
    await page.getByLabel('Buscar clientes').fill('Cliente E2E');
    const clientCard = page.locator('.client-list article').filter({ hasText: 'Cliente E2E' });
    await clientCard.getByRole('button', { name: 'Visualizar' }).click();
    await expect(page.getByRole('heading', { name: 'Cliente E2E' })).toBeVisible();
    await expect(page.getByText(`OS #${orderNumber}`)).toBeVisible();
    const historyCard = page.locator('.clients-history-order').filter({ hasText: `OS #${orderNumber}` });
    await expect(historyCard.getByText('Total: R$ 140,00', { exact: true })).toBeVisible();
    await expect(historyCard.locator('.clients-history-services')).toHaveCount(0);
    await expect(historyCard.getByRole('link', { name: 'Baixar A4 final · Rev. 2', exact: true })).toHaveAttribute('href', `/api/orders/${orderId}/final/2/pdf`);
    const history = await api(page, `/clients/${clientId}`);
    expect(history.body.orders.some((order: { id: number }) => order.id === orderId)).toBeTruthy();
    const historicalOrder = history.body.orders.find((order: { id: number }) => order.id === orderId);
    expect(historicalOrder.items.filter((item: { description: string }) => item.description === 'Formatação E2E')).toHaveLength(1);
    expect(historicalOrder.items[0].unit_price_cents).toBe(14000);
    await page.getByRole('button', { name: 'Pós-Venda' }).click();
    await expect(page.getByRole('heading', { name: 'Pós-Venda & Reputação' })).toBeVisible();
    const lockedRow = page.locator('.post-sale-card').filter({ hasText: `OS ${orderNumber}` });
    await expect(lockedRow).toBeVisible();
    await expect(lockedRow).toHaveCSS('width', '200px');
    await expect(page.locator('.post-sale-grid')).toHaveCSS('justify-content', 'start');
    await expect(lockedRow.locator('.post-sale-state-waiting')).toContainText(/Disponível após \d+ horas/);
    const lockedActions = lockedRow.locator('.post-sale-action[aria-disabled="true"]');
    await expect(lockedActions).toHaveCount(2);
    for (let i = 0; i < 2; i += 1) {
      await expect(lockedActions.nth(i)).not.toHaveAttribute('href');
      await expect(lockedActions.nth(i)).toHaveCSS('pointer-events', 'none');
    }
    const postSale = await api(page, '/post-sales');
    expect(postSale.status).toBe(200);
    const cycle = postSale.body.find((row: { number: string }) => row.number === orderNumber);
    expect(cycle).toBeTruthy();
    expect(cycle.available).toBe(false);
    expect(cycle.eligible_at).toBeTruthy();
    expect(cycle.whatsapp.google).toBeNull();
    const blocked = await api(page, `/post-sales/${cycle.id}/google/confirm`, 'POST', {});
    expect(blocked.status).toBe(409);

    await lockedRow.locator('.post-sale-menu summary').click();
    await lockedRow.getByRole('button', { name: 'Excluir card' }).click();
    const deleteDialog = page.getByRole('dialog', { name: 'Excluir card de Pós-Venda?' });
    await expect(deleteDialog).toBeVisible();
    await deleteDialog.getByRole('button', { name: 'Excluir card', exact: true }).click();
    await expect(lockedRow).toHaveCount(0);
    expect((await api(page, `/orders/${orderId}`)).status).toBe(200);
  });
});
