import { expect, test } from '@playwright/test';
import { api, login, uniqueDocument } from './helpers';

test('etiqueta 40x20: botão discreto, nome local editável e impressão isolada desktop/mobile', async ({ page }) => {
  await login(page);
  const client = await api(page, '/clients', 'POST', { name: 'Allan Cliente Etiqueta', document: uniqueDocument(Date.now()), phone: '35999991234', street: 'Rua de teste' });
  expect(client.status).toBe(201);
  const equipment = (await api(page, '/catalogs/equipment')).body.find((row: any) => row.active);
  const created = await api(page, '/orders', 'POST', { client_id: client.body.id, equipment_type_id: equipment.id, equipment_description: 'Notebook de teste', reported_problem: 'Teste de etiqueta', attendance_type: 'bench', system_password_absent: true, checklist: [] });
  expect(created.status).toBe(201);
  await page.addInitScript(() => { window.print = () => { document.body.dataset.printRequested = 'true'; }; });
  await page.goto('/orders/' + created.body.id);
  const trigger = page.locator('.arl-intake-dates').getByRole('button', { name: 'Imprimir Etiqueta', exact: true });
  await expect(trigger).toBeVisible();
  expect(await trigger.evaluate(node => node.getBoundingClientRect().height)).toBeLessThan(32);
  await trigger.click();
  const dialog = page.getByRole('dialog', { name: 'Imprimir etiqueta', exact: true });
  await expect(dialog.getByLabel('Nome na etiqueta')).toHaveValue('Allan');
  await dialog.getByLabel('Nome na etiqueta').fill('Allan teste');
  const label = dialog.locator('.arl-equipment-label');
  await expect(label).toContainText('OS ' + created.body.number);
  await expect(label).toContainText('ARL Informática');
  const size = await label.boundingBox();
  expect(size!.width).toBeCloseTo(40 * 96 / 25.4, 0);
  expect(size!.height).toBeCloseTo(20 * 96 / 25.4, 0);
  await page.screenshot({ path: 'output/etiquetas/popup-desktop.png' });
  await dialog.getByRole('button', { name: 'Imprimir', exact: true }).click();
  const printFrame = page.frameLocator('iframe[title="Impressão da etiqueta"]');
  await expect(printFrame.locator('body')).toHaveAttribute('data-print-requested', 'true');
  await expect(printFrame.locator('body > *')).toHaveCount(1);
  await expect(printFrame.locator('body')).toHaveText('Allan testeOS ' + created.body.number + 'ARL Informática');
  expect(await printFrame.locator('head style').evaluate(node => node.textContent)).toContain('size:40mm 20mm');
  expect((await api(page, '/clients/' + client.body.id)).body.client.name).toBe('Allan Cliente Etiqueta');
  await dialog.getByRole('button', { name: 'Fechar', exact: true }).click();
  await expect(page.locator('iframe[title="Impressão da etiqueta"]')).toHaveCount(0);
  await trigger.click();
  await expect(dialog.getByLabel('Nome na etiqueta')).toHaveValue('Allan');
  await dialog.getByLabel('Nome na etiqueta').fill('W'.repeat(35));
  expect(await dialog.locator('.arl-equipment-label-name').evaluate(box => box.firstElementChild!.getBoundingClientRect().height <= box.clientHeight)).toBe(true);
  await dialog.getByLabel('Nome na etiqueta').fill('');
  await expect(dialog.getByRole('button', { name: 'Imprimir', exact: true })).toBeDisabled();
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await page.getByLabel('Layout neste dispositivo').selectOption('mobile');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.arl-intake-dates').getByRole('button', { name: 'Imprimir Etiqueta', exact: true }).click();
  await expect(dialog).toBeVisible();
  await expect(dialog.getByLabel('Nome na etiqueta')).toHaveValue('Allan');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'output/etiquetas/popup-mobile.png' });
});
