import { test, expect } from '@playwright/test';
import { api, login, uniqueDocument } from './helpers';

test('financeiro por compra, parcelas recolhidas e produto com histórico em popups', async ({ page }) => {
  await login(page);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const stamp = Date.now();
  const supplier = (await api(page, '/suppliers', 'POST', { name: `Parceiro organizado ${stamp}`, trade_name: 'Distribuidora', document: uniqueDocument(stamp), phone: '35999991234', whatsapp: '35999991234', postal_code: '37160000', street: 'Rua Comercial', number: '20', district: 'Centro', city: 'Campos Gerais', state: 'MG' })).body;
  const product = (await api(page, '/catalogs/products', 'POST', { name: `SSD organizado ${stamp}`, price_cents: 48000, stock_quantity: 0, active: true, warranty_enabled: false })).body;
  const today = new Date().toLocaleDateString('sv-SE', { timeZone: 'America/Sao_Paulo' });
  const purchase = (await api(page, `/suppliers/${supplier.id}/purchases`, 'POST', { request_key: crypto.randomUUID(), purchased_on: today, received_now: true, reference: 'NF-32', payment_terms: 'installments', payment_method: 'boleto', items: [{ product_id: product.id, quantity: 1, unit_cost_cents: 32000, lot: 'LOTE-32' }], installments: Array.from({ length: 32 }, () => ({ amount_cents: 1000, due_on: today })) })).body;
  expect(purchase.id).toBeTruthy();
  await api(page, `/suppliers/${supplier.id}/purchases`, 'POST', { request_key: crypto.randomUUID(), purchased_on: today, received_now: true, payment_terms: 'cash', payment_method: 'pix', items: [{ product_id: product.id, quantity: 1, unit_cost_cents: 20000 }], installments: [{ amount_cents: 20000, due_on: today }] });
  await page.goto(`/suppliers?supplier=${supplier.id}`);
  await page.getByRole('tab', { name: 'Financeiro', exact: true }).click();
  await expect(page.locator('.supplier-finance-row')).toHaveCount(2);
  const row = page.locator('.supplier-finance-row').filter({ hasText: 'NF-32' });
  await expect(row).toContainText('32 parcelas');
  await expect(row).toContainText('R$ 320,00');
  await page.screenshot({ path: 'output/fornecedores/financeiro-por-compra.png' });
  await row.click();
  const modal = page.getByRole('dialog', { name: `Compra #${String(purchase.id).padStart(6, "0")}`, exact: true });
  await expect(modal).toBeVisible();
  await expect(modal.locator('.supplier-installment-history')).toHaveCount(0);
  await modal.getByRole('button', { name: /Ver parcelas/ }).click();
  await expect(modal.locator('.supplier-installment-history')).toHaveCount(32);
  await expect(modal.locator('.supplier-installment-history').last()).toContainText('Parcela 32/32');
  await modal.locator('.supplier-installment-history').first().getByRole('button', { name: 'Registrar pagamento', exact: true }).click();
  await modal.getByRole('button', { name: 'Confirmar pagamento', exact: true }).click();
  await expect(modal.locator('.supplier-installment-history').first()).toContainText('Paga em');
  await modal.getByRole('button', { name: 'Itens e dados', exact: true }).click();
  await expect(modal).toContainText('LOTE-32');
  const box = await modal.boundingBox();
  expect(box?.y).toBeGreaterThanOrEqual(0);
  expect((box?.y || 0) + (box?.height || 0)).toBeLessThanOrEqual(1000);
  await page.screenshot({ path: 'output/fornecedores/detalhes-compra-popup.png' });
  await modal.getByRole('button', { name: 'Recebimentos (1)', exact: true }).click();
  await expect(modal.getByRole('heading', { name: 'Recebimentos registrados' })).toBeVisible();
  await modal.getByRole('button', { name: 'Fechar compra', exact: true }).click();
  await expect(row).toContainText('1 pagas');
  await page.getByRole('tab', { name: 'Produtos adquiridos', exact: true }).click();
  await page.locator('.supplier-product-open').click();
  const productModal = page.getByRole('dialog', { name: product.name, exact: true });
  await expect(productModal).toContainText('R$ 480,00');
  await expect(productModal).toContainText('2 unidades');
  await productModal.getByRole('button', { name: 'Compras e custos', exact: true }).click();
  await expect(productModal.locator('.supplier-compact-row')).toHaveCount(2);
  await expect(productModal).toContainText('LOTE-32');
  await page.screenshot({ path: 'output/fornecedores/produto-popup-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'output/fornecedores/produto-popup-mobile.png' });
  expect(await productModal.evaluate(e => e.scrollWidth <= e.clientWidth + 1)).toBe(true);
  expect(await productModal.locator('.supplier-dialog-body').evaluate(e => e.scrollWidth <= e.clientWidth + 1)).toBe(true);
  await productModal.locator('.supplier-compact-row').filter({ hasText: 'LOTE-32' }).click();
  await expect(modal).toBeVisible();
  expect(await modal.evaluate(e => e.scrollWidth <= e.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: 'output/fornecedores/compra-popup-mobile.png' });
  await page.keyboard.press('Escape');
  await expect(modal).not.toBeVisible();
});
