<?php

use App\Http\Controllers\BudgetController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\FinalizationController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\ServiceOrderController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\TechnicalReportController;
use App\Http\Controllers\TechnicalReportTemplateController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function () {
    Route::get('/clients', [ClientController::class, 'index']);
    Route::post('/clients', [ClientController::class, 'store']);
    Route::put('/clients/{client}', [ClientController::class, 'update']);
    Route::get('/catalogs/checklist', [CatalogController::class, 'checklist']);
    Route::get('/catalogs/{catalog}', [CatalogController::class, 'index']);
    Route::post('/catalogs/{catalog}', [CatalogController::class, 'store']);
    Route::patch('/catalogs/{catalog}/{id}', [CatalogController::class, 'update']);
    Route::get('/orders', [ServiceOrderController::class, 'index']);
    Route::post('/orders', [ServiceOrderController::class, 'store']);
    Route::get('/orders/{order}', [ServiceOrderController::class, 'show']);
    Route::post('/orders/{order}/photos', [ServiceOrderController::class, 'uploadPhoto']);
    Route::get('/orders/{order}/photos/{photo}', [ServiceOrderController::class, 'photo']);
    Route::patch('/orders/{order}/status', [ServiceOrderController::class, 'updateStatus']);
    Route::post('/orders/{order}/finalize', [FinalizationController::class, 'store']);
    Route::get('/orders/{order}/payment', [FinanceController::class, 'payment']);
    Route::post('/orders/{order}/payment', [FinanceController::class, 'pay']);
    Route::post('/finance/quick-entry', [FinanceController::class, 'quickEntry']);
    Route::get('/finance/overview', [FinanceController::class, 'overview']);
    Route::get('/finance/daily', [FinanceController::class, 'transactions']);
    Route::get('/finance/month', [FinanceController::class, 'month']);
    Route::post('/finance/transactions/{transaction}/adjust', [FinanceController::class, 'adjust']);
    Route::post('/finance/reports', [FinanceController::class, 'issueReport']);
    Route::get('/finance/reports/{document}/pdf', [FinanceController::class, 'report']);
    Route::get('/settings', [SettingsController::class, 'show']);
    Route::put('/settings', [SettingsController::class, 'update']);
    Route::post('/settings/logo', [SettingsController::class, 'logo']);
    Route::get('/settings/logo/{variant}', [SettingsController::class, 'logoFile']);
    Route::get('/orders/{order}/term', [DocumentController::class, 'term']);
    Route::get('/orders/{order}/budgets', [BudgetController::class, 'index']);
    Route::post('/orders/{order}/budgets', [BudgetController::class, 'store']);
    Route::patch('/orders/{order}/budgets/{revision}/status', [BudgetController::class, 'status']);
    Route::get('/orders/{order}/budgets/{revision}/pdf', [DocumentController::class, 'budget']);
    Route::get('/orders/{order}/documents', [DocumentController::class, 'index']);
    Route::get('/orders/{order}/final/{revision}/pdf', [DocumentController::class, 'finalDocument']);
    Route::get('/orders/{order}/reports', [TechnicalReportController::class, 'index']);
    Route::post('/orders/{order}/reports', [TechnicalReportController::class, 'store']);
    Route::put('/orders/{order}/reports/{revision}', [TechnicalReportController::class, 'update']);
    Route::post('/orders/{order}/reports/{revision}/issue', [TechnicalReportController::class, 'issue']);
    Route::get('/orders/{order}/reports/{revision}/pdf', [DocumentController::class, 'technicalReport']);
    Route::get('/report-templates', [TechnicalReportTemplateController::class, 'index']);
    Route::post('/report-templates', [TechnicalReportTemplateController::class, 'store']);
    Route::put('/report-templates/{template}', [TechnicalReportTemplateController::class, 'update']);
    Route::post('/report-templates/{template}/duplicate', [TechnicalReportTemplateController::class, 'duplicate']);
});
